/* Generated By:JJTree&JavaCC: Do not edit this line. AngularParserConstants.java */
package ccbus.tool.parser.typescript;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AngularParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 9;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 10;
  /** RegularExpression Id. */
  int ABSTRACT = 12;
  /** RegularExpression Id. */
  int ASSERT = 13;
  /** RegularExpression Id. */
  int ANY = 14;
  /** RegularExpression Id. */
  int BOOLEAN = 15;
  /** RegularExpression Id. */
  int BREAK = 16;
  /** RegularExpression Id. */
  int BYTE = 17;
  /** RegularExpression Id. */
  int CASE = 18;
  /** RegularExpression Id. */
  int CATCH = 19;
  /** RegularExpression Id. */
  int CHAR = 20;
  /** RegularExpression Id. */
  int EXPORT = 21;
  /** RegularExpression Id. */
  int CLASS = 22;
  /** RegularExpression Id. */
  int CONST = 23;
  /** RegularExpression Id. */
  int CONTINUE = 24;
  /** RegularExpression Id. */
  int _DEFAULT = 25;
  /** RegularExpression Id. */
  int DO = 26;
  /** RegularExpression Id. */
  int DOUBLE = 27;
  /** RegularExpression Id. */
  int ELSE = 28;
  /** RegularExpression Id. */
  int ENUM = 29;
  /** RegularExpression Id. */
  int EXTENDS = 30;
  /** RegularExpression Id. */
  int FALSE = 31;
  /** RegularExpression Id. */
  int FINAL = 32;
  /** RegularExpression Id. */
  int FINALLY = 33;
  /** RegularExpression Id. */
  int FLOAT = 34;
  /** RegularExpression Id. */
  int FOR = 35;
  /** RegularExpression Id. */
  int GOTO = 36;
  /** RegularExpression Id. */
  int IF = 37;
  /** RegularExpression Id. */
  int IMPLEMENTS = 38;
  /** RegularExpression Id. */
  int IMPORT = 39;
  /** RegularExpression Id. */
  int INSTANCEOF = 40;
  /** RegularExpression Id. */
  int INT = 41;
  /** RegularExpression Id. */
  int INTERFACE = 42;
  /** RegularExpression Id. */
  int LONG = 43;
  /** RegularExpression Id. */
  int NATIVE = 44;
  /** RegularExpression Id. */
  int NEW = 45;
  /** RegularExpression Id. */
  int NUMBER = 46;
  /** RegularExpression Id. */
  int NULL = 47;
  /** RegularExpression Id. */
  int PACKAGE = 48;
  /** RegularExpression Id. */
  int PRIVATE = 49;
  /** RegularExpression Id. */
  int PROTECTED = 50;
  /** RegularExpression Id. */
  int PUBLIC = 51;
  /** RegularExpression Id. */
  int RETURN = 52;
  /** RegularExpression Id. */
  int STRING = 53;
  /** RegularExpression Id. */
  int SYMBOL = 54;
  /** RegularExpression Id. */
  int SHORT = 55;
  /** RegularExpression Id. */
  int STATIC = 56;
  /** RegularExpression Id. */
  int STRICTFP = 57;
  /** RegularExpression Id. */
  int SUPER = 58;
  /** RegularExpression Id. */
  int SWITCH = 59;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 60;
  /** RegularExpression Id. */
  int THIS = 61;
  /** RegularExpression Id. */
  int THROW = 62;
  /** RegularExpression Id. */
  int THROWS = 63;
  /** RegularExpression Id. */
  int TRANSIENT = 64;
  /** RegularExpression Id. */
  int TRUE = 65;
  /** RegularExpression Id. */
  int TRY = 66;
  /** RegularExpression Id. */
  int VOID = 67;
  /** RegularExpression Id. */
  int VOLATILE = 68;
  /** RegularExpression Id. */
  int WHILE = 69;
  /** RegularExpression Id. */
  int LET = 70;
  /** RegularExpression Id. */
  int OF = 71;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 72;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 73;
  /** RegularExpression Id. */
  int HEX_LITERAL = 74;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 75;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 76;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 77;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 78;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 79;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 80;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 81;
  /** RegularExpression Id. */
  int STRING_LITERAL = 82;
  /** RegularExpression Id. */
  int IDENTIFIER = 83;
  /** RegularExpression Id. */
  int LETTER = 84;
  /** RegularExpression Id. */
  int PART_LETTER = 85;
  /** RegularExpression Id. */
  int LPAREN = 86;
  /** RegularExpression Id. */
  int RPAREN = 87;
  /** RegularExpression Id. */
  int LBRACE = 88;
  /** RegularExpression Id. */
  int RBRACE = 89;
  /** RegularExpression Id. */
  int LBRACKET = 90;
  /** RegularExpression Id. */
  int RBRACKET = 91;
  /** RegularExpression Id. */
  int SEMICOLON = 92;
  /** RegularExpression Id. */
  int COMMA = 93;
  /** RegularExpression Id. */
  int DOT = 94;
  /** RegularExpression Id. */
  int AT = 95;
  /** RegularExpression Id. */
  int ASSIGN = 96;
  /** RegularExpression Id. */
  int LT = 97;
  /** RegularExpression Id. */
  int BANG = 98;
  /** RegularExpression Id. */
  int TILDE = 99;
  /** RegularExpression Id. */
  int HOOK = 100;
  /** RegularExpression Id. */
  int COLON = 101;
  /** RegularExpression Id. */
  int EQ = 102;
  /** RegularExpression Id. */
  int LE = 103;
  /** RegularExpression Id. */
  int GE = 104;
  /** RegularExpression Id. */
  int NE = 105;
  /** RegularExpression Id. */
  int SC_OR = 106;
  /** RegularExpression Id. */
  int SC_AND = 107;
  /** RegularExpression Id. */
  int INCR = 108;
  /** RegularExpression Id. */
  int DECR = 109;
  /** RegularExpression Id. */
  int PLUS = 110;
  /** RegularExpression Id. */
  int MINUS = 111;
  /** RegularExpression Id. */
  int STAR = 112;
  /** RegularExpression Id. */
  int SLASH = 113;
  /** RegularExpression Id. */
  int BIT_AND = 114;
  /** RegularExpression Id. */
  int BIT_OR = 115;
  /** RegularExpression Id. */
  int XOR = 116;
  /** RegularExpression Id. */
  int REM = 117;
  /** RegularExpression Id. */
  int LSHIFT = 118;
  /** RegularExpression Id. */
  int PLUSASSIGN = 119;
  /** RegularExpression Id. */
  int MINUSASSIGN = 120;
  /** RegularExpression Id. */
  int STARASSIGN = 121;
  /** RegularExpression Id. */
  int SLASHASSIGN = 122;
  /** RegularExpression Id. */
  int ANDASSIGN = 123;
  /** RegularExpression Id. */
  int ORASSIGN = 124;
  /** RegularExpression Id. */
  int XORASSIGN = 125;
  /** RegularExpression Id. */
  int REMASSIGN = 126;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 127;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 128;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 129;
  /** RegularExpression Id. */
  int ELLIPSIS = 130;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 131;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 132;
  /** RegularExpression Id. */
  int GT = 133;
  /** RegularExpression Id. */
  int STUFF_TO_IGNORE = 135;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 11>",
    "\"abstract\"",
    "\"assert\"",
    "\"any\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"export\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"packa\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"number\"",
    "\"null\"",
    "\"packa\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"string\"",
    "\"symbol\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"let\"",
    "\"of\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
    "\"\\u001a\"",
    "<STUFF_TO_IGNORE>",
  };

}
