/* Generated By:JJTree: Do not edit this line. ASTAssignmentOperator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTAssignmentOperator extends SimpleNode {
  public ASTAssignmentOperator(int id) {
    super(id);
  }

  public ASTAssignmentOperator(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6bebd266b847e68b7761ee10a8978e31 (do not edit this line) */
