/* Generated By:JJTree: Do not edit this line. ASTAnnotation.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTAnnotation extends SimpleNode {
  public ASTAnnotation(int id) {
    super(id);
  }

  public ASTAnnotation(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d0cf528c201235535aeef860b4c91cc7 (do not edit this line) */
