/* Generated By:JJTree: Do not edit this line. ASTAdditiveTokens.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTAdditiveTokens extends SimpleNode {
  public ASTAdditiveTokens(int id) {
    super(id);
  }

  public ASTAdditiveTokens(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a33a0e9acd28e1a94abecc8ab22d816c (do not edit this line) */
