/* Generated By:JJTree: Do not edit this line. ASTBreakToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTBreakToken extends SimpleNode {
  public ASTBreakToken(int id) {
    super(id);
  }

  public ASTBreakToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5e2f0ea69c4522817fdc47d8dbecb018 (do not edit this line) */
