/* Generated By:JJTree: Do not edit this line. ASTBreakStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTBreakStatement extends SimpleNode {
  public ASTBreakStatement(int id) {
    super(id);
  }

  public ASTBreakStatement(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1ab52b0999c154aff603107486a9d27b (do not edit this line) */
