/* Generated By:JJTree: Do not edit this line. ASTBitAndToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTBitAndToken extends SimpleNode {
  public ASTBitAndToken(int id) {
    super(id);
  }

  public ASTBitAndToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cd01c9f65a080d9d1ee20deeb315f6d5 (do not edit this line) */
