/* Generated By:JJTree: Do not edit this line. ASTBracket.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTBracket extends SimpleNode {
  public ASTBracket(int id) {
    super(id);
  }

  public ASTBracket(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f34ee36b532246dd0e618307de2a5d14 (do not edit this line) */
