/* Generated By:JJTree: Do not edit this line. ASTBlock.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTBlock extends SimpleNode {
  public ASTBlock(int id) {
    super(id);
  }

  public ASTBlock(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b93cb73e661e900a1622dafb737b0814 (do not edit this line) */
