/* Generated By:JJTree: Do not edit this line. ASTBitOrToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTBitOrToken extends SimpleNode {
  public ASTBitOrToken(int id) {
    super(id);
  }

  public ASTBitOrToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9b979d5619dab706892bf3e6f0dbda81 (do not edit this line) */
