/* Generated By:JJTree: Do not edit this line. ASTBlockStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTBlockStatement extends SimpleNode {
  public ASTBlockStatement(int id) {
    super(id);
  }

  public ASTBlockStatement(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a37a5a1d1534bb746175f5ba5bb5db5e (do not edit this line) */
