/* Generated By:JJTree: Do not edit this line. ASTClassOrInterfaceType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTClassOrInterfaceType extends SimpleNode {
  public ASTClassOrInterfaceType(int id) {
    super(id);
  }

  public ASTClassOrInterfaceType(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b968847cc439d6a20a95f4ac0b80aa41 (do not edit this line) */
