/* Generated By:JJTree: Do not edit this line. ASTClassOrInterfaceBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTClassOrInterfaceBody extends SimpleNode {
  public ASTClassOrInterfaceBody(int id) {
    super(id);
  }

  public ASTClassOrInterfaceBody(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8c667fd591f3e1c3e1c966072579a1af (do not edit this line) */
