/* Generated By:JJTree: Do not edit this line. ASTCatchToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTCatchToken extends SimpleNode {
  public ASTCatchToken(int id) {
    super(id);
  }

  public ASTCatchToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0ca080e840624f7657b318fdc27e065d (do not edit this line) */
