/* Generated By:JJTree: Do not edit this line. ASTClassOrInterfaceDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTClassOrInterfaceDeclaration extends SimpleNode {
  public ASTClassOrInterfaceDeclaration(int id) {
    super(id);
  }

  public ASTClassOrInterfaceDeclaration(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e55d9ff3082200372641933d951ffa5c (do not edit this line) */
