/* Generated By:JJTree: Do not edit this line. ASTCaseToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTCaseToken extends SimpleNode {
  public ASTCaseToken(int id) {
    super(id);
  }

  public ASTCaseToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d53be44e26103e94bca86eac2c4f854e (do not edit this line) */
