/* Generated By:JJTree: Do not edit this line. ASTContinueStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTContinueStatement extends SimpleNode {
  public ASTContinueStatement(int id) {
    super(id);
  }

  public ASTContinueStatement(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1da94985487f84a8dc524e97ec8f7a93 (do not edit this line) */
