/* Generated By:JJTree: Do not edit this line. ASTCastExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTCastExpression extends SimpleNode {
  public ASTCastExpression(int id) {
    super(id);
  }

  public ASTCastExpression(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f3bcbd5c0c5b04647696a79937e56981 (do not edit this line) */
