/* Generated By:JJTree: Do not edit this line. ASTColonToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTColonToken extends SimpleNode {
  public ASTColonToken(int id) {
    super(id);
  }

  public ASTColonToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9764070b5ad9d123cf1499786081ae06 (do not edit this line) */
