/* Generated By:JJTree: Do not edit this line. ASTConditionalExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTConditionalExpression extends SimpleNode {
  public ASTConditionalExpression(int id) {
    super(id);
  }

  public ASTConditionalExpression(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a49b9e2e0e8fdf0c44de6f4a1951889b (do not edit this line) */
