/* Generated By:JJTree: Do not edit this line. ASTCommaToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTCommaToken extends SimpleNode {
  public ASTCommaToken(int id) {
    super(id);
  }

  public ASTCommaToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ce2618ae963b0cb628959782a69339bd (do not edit this line) */
