/* Generated By:JJTree: Do not edit this line. ASTDoStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTDoStatement extends SimpleNode {
  public ASTDoStatement(int id) {
    super(id);
  }

  public ASTDoStatement(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e760839be06896d48c7c4dd6de771a81 (do not edit this line) */
