/* Generated By:JJTree: Do not edit this line. ASTDefaultToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTDefaultToken extends SimpleNode {
  public ASTDefaultToken(int id) {
    super(id);
  }

  public ASTDefaultToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=84e87bc15eea50777f71cfd4a80d607b (do not edit this line) */
