/* Generated By:JJTree: Do not edit this line. ASTDotToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTDotToken extends SimpleNode {
  public ASTDotToken(int id) {
    super(id);
  }

  public ASTDotToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c5bdf8a27939ac674f3abf549b2065f (do not edit this line) */
