/* Generated By:JJTree: Do not edit this line. ASTDoToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTDoToken extends SimpleNode {
  public ASTDoToken(int id) {
    super(id);
  }

  public ASTDoToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cd9fc24e2017dd8ddeb36e878e845bd8 (do not edit this line) */
