/* Generated By:JJTree: Do not edit this line. ASTExtendsList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTExtendsList extends SimpleNode {
  public ASTExtendsList(int id) {
    super(id);
  }

  public ASTExtendsList(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6e84e9388d3c2604b4aefc6ac20897d7 (do not edit this line) */
