/* Generated By:JJTree: Do not edit this line. ASTEqualityTokens.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTEqualityTokens extends SimpleNode {
  public ASTEqualityTokens(int id) {
    super(id);
  }

  public ASTEqualityTokens(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1ee29b1a53640f0698192d0aa02c1545 (do not edit this line) */
