/* Generated By:JJTree: Do not edit this line. ASTElseToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTElseToken extends SimpleNode {
  public ASTElseToken(int id) {
    super(id);
  }

  public ASTElseToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=570fb340795dd64aae1ea1e285e27efd (do not edit this line) */
