/* Generated By:JJTree: Do not edit this line. ASTEqualityExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTEqualityExpression extends SimpleNode {
  public ASTEqualityExpression(int id) {
    super(id);
  }

  public ASTEqualityExpression(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7dac5bf3aa03406d356f08eff2a135ab (do not edit this line) */
