/* Generated By:JJTree: Do not edit this line. ASTFormalParameter.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTFormalParameter extends SimpleNode {
  public ASTFormalParameter(int id) {
    super(id);
  }

  public ASTFormalParameter(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bfc4d0e8385d100b7f1df8b2e29078d7 (do not edit this line) */
