/* Generated By:JJTree: Do not edit this line. ASTForUpdate.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTForUpdate extends SimpleNode {
  public ASTForUpdate(int id) {
    super(id);
  }

  public ASTForUpdate(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=26b51df76cf86ef206eb6ff2d61b57a8 (do not edit this line) */
