/* Generated By:JJTree: Do not edit this line. ASTFieldDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTFieldDeclaration extends SimpleNode {
  public ASTFieldDeclaration(int id) {
    super(id);
  }

  public ASTFieldDeclaration(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5886843d45c623234e0eeca60d7a0b68 (do not edit this line) */
