/* Generated By:JJTree: Do not edit this line. ASTForStatementRange.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTForStatementRange extends SimpleNode {
  public ASTForStatementRange(int id) {
    super(id);
  }

  public ASTForStatementRange(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6ab47ad021e92479681ed827ce84a475 (do not edit this line) */
