/* Generated By:JJTree: Do not edit this line. ASTFinallyToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTFinallyToken extends SimpleNode {
  public ASTFinallyToken(int id) {
    super(id);
  }

  public ASTFinallyToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fcd374749e5830329f07e8bed0385aaf (do not edit this line) */
