/* Generated By:JJTree: Do not edit this line. ASTForStatementLoop.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTForStatementLoop extends SimpleNode {
  public ASTForStatementLoop(int id) {
    super(id);
  }

  public ASTForStatementLoop(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=90864f45590cc1ede2bd08354c87e810 (do not edit this line) */
