/* Generated By:JJTree: Do not edit this line. ASTIncrToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTIncrToken extends SimpleNode {
  public ASTIncrToken(int id) {
    super(id);
  }

  public ASTIncrToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=67a0ef1d009a4773655eae05174ac783 (do not edit this line) */
