/* Generated By:JJTree: Do not edit this line. ASTIfToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTIfToken extends SimpleNode {
  public ASTIfToken(int id) {
    super(id);
  }

  public ASTIfToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8c3fb394225e3c238908da7910a87361 (do not edit this line) */
