/* Generated By:JJTree: Do not edit this line. ASTImplementsList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTImplementsList extends SimpleNode {
  public ASTImplementsList(int id) {
    super(id);
  }

  public ASTImplementsList(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2109adfc8f19b640fc1368de20a77560 (do not edit this line) */
