/* Generated By:JJTree: Do not edit this line. ASTLParenToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTLParenToken extends SimpleNode {
  public ASTLParenToken(int id) {
    super(id);
  }

  public ASTLParenToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9dc76a4d056877784d5c7d9fa868dee2 (do not edit this line) */
