/* Generated By:JJTree: Do not edit this line. ASTLBracketToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTLBracketToken extends SimpleNode {
  public ASTLBracketToken(int id) {
    super(id);
  }

  public ASTLBracketToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=528b1196fcaeac8b587abbba2d579bc4 (do not edit this line) */
