/* Generated By:JJTree: Do not edit this line. ASTLocalVariableDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTLocalVariableDeclaration extends SimpleNode {
  public ASTLocalVariableDeclaration(int id) {
    super(id);
  }

  public ASTLocalVariableDeclaration(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=58929ff6b3078ed74df985fa0f65b1eb (do not edit this line) */
