/* Generated By:JJTree: Do not edit this line. ASTLShiftToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTLShiftToken extends SimpleNode {
  public ASTLShiftToken(int id) {
    super(id);
  }

  public ASTLShiftToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8e47132de619bded3703f85b78884151 (do not edit this line) */
