/* Generated By:JJTree: Do not edit this line. ASTModifiers.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTModifiers extends SimpleNode {
  public ASTModifiers(int id) {
    super(id);
  }

  public ASTModifiers(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=854ad87f8a0ecb8be3fea5d1f584ba69 (do not edit this line) */
