/* Generated By:JJTree: Do not edit this line. ASTMultiplicativeTokens.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTMultiplicativeTokens extends SimpleNode {
  public ASTMultiplicativeTokens(int id) {
    super(id);
  }

  public ASTMultiplicativeTokens(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4b98e9fa272c611695af0906dcf50f3a (do not edit this line) */
