/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTMethodDeclarator extends SimpleNode {
  public ASTMethodDeclarator(int id) {
    super(id);
  }

  public ASTMethodDeclarator(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9b6e7866457123d3c3224d7f3de62bf3 (do not edit this line) */
