/* Generated By:JJTree: Do not edit this line. ASTModifier.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTModifier extends SimpleNode {
  public ASTModifier(int id) {
    super(id);
  }

  public ASTModifier(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=50ee121695e94f5e1a5aa891ab24d985 (do not edit this line) */
