/* Generated By:JJTree: Do not edit this line. ASTMemberSelector.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTMemberSelector extends SimpleNode {
  public ASTMemberSelector(int id) {
    super(id);
  }

  public ASTMemberSelector(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c9a601a05c2722f73820f016406b8c0 (do not edit this line) */
