/* Generated By:JJTree: Do not edit this line. ASTNewToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTNewToken extends SimpleNode {
  public ASTNewToken(int id) {
    super(id);
  }

  public ASTNewToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b77182e6c6148140c9679747da39d013 (do not edit this line) */
