/* Generated By:JJTree: Do not edit this line. ASTNotPlusMinusTokens.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTNotPlusMinusTokens extends SimpleNode {
  public ASTNotPlusMinusTokens(int id) {
    super(id);
  }

  public ASTNotPlusMinusTokens(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=811a96f8b00110a436ee3ccc22e7944b (do not edit this line) */
