/* Generated By:JJTree: Do not edit this line. ASTNullLiteral.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTNullLiteral extends SimpleNode {
  public ASTNullLiteral(int id) {
    super(id);
  }

  public ASTNullLiteral(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=16e57ab907d211e0582b99b9be2f85ed (do not edit this line) */
