/* Generated By:JJTree: Do not edit this line. ASTOrToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTOrToken extends SimpleNode {
  public ASTOrToken(int id) {
    super(id);
  }

  public ASTOrToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2e739e554778cffa6aba1efe189e6ff7 (do not edit this line) */
