/* Generated By:JJTree: Do not edit this line. ASTPrimaryExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTPrimaryExpression extends SimpleNode {
  public ASTPrimaryExpression(int id) {
    super(id);
  }

  public ASTPrimaryExpression(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bc408bb25b63b837ef836fdf1d3720dc (do not edit this line) */
