/* Generated By:JJTree: Do not edit this line. ASTPrimaryPrefix.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTPrimaryPrefix extends SimpleNode {
  public ASTPrimaryPrefix(int id) {
    super(id);
  }

  public ASTPrimaryPrefix(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=60ee26e7670c9e2d41da91cb6097cb9d (do not edit this line) */
