/* Generated By:JJTree: Do not edit this line. ASTPrimitiveType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTPrimitiveType extends SimpleNode {
  public ASTPrimitiveType(int id) {
    super(id);
  }

  public ASTPrimitiveType(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a1513825f06e8ad7aa7f2041c0e8951d (do not edit this line) */
