/* Generated By:JJTree: Do not edit this line. ASTPrimarySuffix.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTPrimarySuffix extends SimpleNode {
  public ASTPrimarySuffix(int id) {
    super(id);
  }

  public ASTPrimarySuffix(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=058883cc4be35d0820aa78be6a65dba6 (do not edit this line) */
