/* Generated By:JJTree: Do not edit this line. ASTRelationTokens.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTRelationTokens extends SimpleNode {
  public ASTRelationTokens(int id) {
    super(id);
  }

  public ASTRelationTokens(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4b7a265ef57f40d157a53f86723e3a53 (do not edit this line) */
