/* Generated By:JJTree: Do not edit this line. ASTResultType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTResultType extends SimpleNode {
  public ASTResultType(int id) {
    super(id);
  }

  public ASTResultType(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f0530c21ddc265e2c4c93a9d67095dd6 (do not edit this line) */
