/* Generated By:JJTree: Do not edit this line. ASTRSIGNEDSHIFT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTRSIGNEDSHIFT extends SimpleNode {
  public ASTRSIGNEDSHIFT(int id) {
    super(id);
  }

  public ASTRSIGNEDSHIFT(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bf8539cb4d6970e478880ea597d502da (do not edit this line) */
