/* Generated By:JJTree: Do not edit this line. ASTRParenToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTRParenToken extends SimpleNode {
  public ASTRParenToken(int id) {
    super(id);
  }

  public ASTRParenToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=104a0fa3d43126e2ea0406d7ed9354d8 (do not edit this line) */
