/* Generated By:JJTree: Do not edit this line. ASTSwitchToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTSwitchToken extends SimpleNode {
  public ASTSwitchToken(int id) {
    super(id);
  }

  public ASTSwitchToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=50c2fdac869e62eff9e22a75a5746e00 (do not edit this line) */
