/* Generated By:JJTree: Do not edit this line. ASTSemicolonToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTSemicolonToken extends SimpleNode {
  public ASTSemicolonToken(int id) {
    super(id);
  }

  public ASTSemicolonToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8a3064a64ac076a2d52bc03c5cb9471a (do not edit this line) */
