/* Generated By:JJTree: Do not edit this line. ASTTypeArgument.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTTypeArgument extends SimpleNode {
  public ASTTypeArgument(int id) {
    super(id);
  }

  public ASTTypeArgument(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=81fd0e1ad3409b4c953c20360b6f4601 (do not edit this line) */
