/* Generated By:JJTree: Do not edit this line. ASTTryToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTTryToken extends SimpleNode {
  public ASTTryToken(int id) {
    super(id);
  }

  public ASTTryToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e042c7e6d9c5eef0db5a5722fd0898c8 (do not edit this line) */
