/* Generated By:JJTree: Do not edit this line. ASTThrowToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTThrowToken extends SimpleNode {
  public ASTThrowToken(int id) {
    super(id);
  }

  public ASTThrowToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fd1ba17476d9dbf1846630f09ba8dc46 (do not edit this line) */
