/* Generated By:JJTree: Do not edit this line. ASTTypeIdentifier.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTTypeIdentifier extends SimpleNode {
  public ASTTypeIdentifier(int id) {
    super(id);
  }

  public ASTTypeIdentifier(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5102aeb0dbbd47409452b8d65069f053 (do not edit this line) */
