/* Generated By:JJTree: Do not edit this line. ASTUnaryTokens.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTUnaryTokens extends SimpleNode {
  public ASTUnaryTokens(int id) {
    super(id);
  }

  public ASTUnaryTokens(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d6ac925eb5e9206990f10be7187177c2 (do not edit this line) */
