/* Generated By:JJTree: Do not edit this line. ASTUnaryExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTUnaryExpression extends SimpleNode {
  public ASTUnaryExpression(int id) {
    super(id);
  }

  public ASTUnaryExpression(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f799949458307b5ef1fbff68c528b2e8 (do not edit this line) */
