/* Generated By:JJTree: Do not edit this line. ASTVoidType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTVoidType extends SimpleNode {
  public ASTVoidType(int id) {
    super(id);
  }

  public ASTVoidType(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=335d277cada59b3579b295324c7a4a18 (do not edit this line) */
