/* Generated By:JJTree: Do not edit this line. ASTVariableDeclarator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTVariableDeclarator extends SimpleNode {
  public ASTVariableDeclarator(int id) {
    super(id);
  }

  public ASTVariableDeclarator(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=559d036ec921249170f24d41b2c82616 (do not edit this line) */
