/* Generated By:JJTree: Do not edit this line. ASTVariableDeclaratorId.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTVariableDeclaratorId extends SimpleNode {
  public ASTVariableDeclaratorId(int id) {
    super(id);
  }

  public ASTVariableDeclaratorId(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=84e6d5384504ee749fb34a831c4411ad (do not edit this line) */
