/* Generated By:JJTree: Do not edit this line. ASTWhileToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.typescript;

public
class ASTWhileToken extends SimpleNode {
  public ASTWhileToken(int id) {
    super(id);
  }

  public ASTWhileToken(AngularParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=73aac5d2e5a17b1776c7646f5172481c (do not edit this line) */
