/* Generated By:JJTree: Do not edit this line. ASTArrayDimsAndInits.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTArrayDimsAndInits extends SimpleNode {
  public ASTArrayDimsAndInits(int id) {
    super(id);
  }

  public ASTArrayDimsAndInits(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0c36c1712644bed622c6542f642ff736 (do not edit this line) */
