/* Generated By:JJTree: Do not edit this line. ASTAdditiveTokens.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTAdditiveTokens extends SimpleNode {
  public ASTAdditiveTokens(int id) {
    super(id);
  }

  public ASTAdditiveTokens(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3b06ca8e763b6cba06221b21595e486a (do not edit this line) */
