/* Generated By:JJTree: Do not edit this line. ASTArrayInitializer.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTArrayInitializer extends SimpleNode {
  public ASTArrayInitializer(int id) {
    super(id);
  }

  public ASTArrayInitializer(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f9b5ad1af66ebfe0e5652164c5c21798 (do not edit this line) */
