/* Generated By:JJTree: Do not edit this line. ASTAnnotation.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTAnnotation extends SimpleNode {
  public ASTAnnotation(int id) {
    super(id);
  }

  public ASTAnnotation(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8e47efc8888eec8c9bffe9e565ced18e (do not edit this line) */
