/* Generated By:JJTree: Do not edit this line. ASTAssignmentOperator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTAssignmentOperator extends SimpleNode {
  public ASTAssignmentOperator(int id) {
    super(id);
  }

  public ASTAssignmentOperator(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ad8dc885d440efcb0f459e0246f1defa (do not edit this line) */
