/* Generated By:JJTree: Do not edit this line. ASTAnnotationTypeBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTAnnotationTypeBody extends SimpleNode {
  public ASTAnnotationTypeBody(int id) {
    super(id);
  }

  public ASTAnnotationTypeBody(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6b5eff70d1c4ea9d2e46e6626eab4a15 (do not edit this line) */
