/* Generated By:JJTree: Do not edit this line. ASTAnnotationTypeDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTAnnotationTypeDeclaration extends SimpleNode {
  public ASTAnnotationTypeDeclaration(int id) {
    super(id);
  }

  public ASTAnnotationTypeDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=728f477945e9a822c385da1d5723871a (do not edit this line) */
