/* Generated By:JJTree: Do not edit this line. ASTAdditiveOperators.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTAdditiveOperators extends SimpleNode {
  public ASTAdditiveOperators(int id) {
    super(id);
  }

  public ASTAdditiveOperators(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3a9a7cdc228c5f35cffac98fe1b27ce5 (do not edit this line) */
