/* Generated By:JJTree: Do not edit this line. ASTArrowToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTArrowToken extends SimpleNode {
  public ASTArrowToken(int id) {
    super(id);
  }

  public ASTArrowToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cc6aa39f0d2feaab51e766b369c0dd21 (do not edit this line) */
