/* Generated By:JJTree: Do not edit this line. ASTArgumentList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTArgumentList extends SimpleNode {
  public ASTArgumentList(int id) {
    super(id);
  }

  public ASTArgumentList(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b6752360c4988a658b68205a8cb52ce9 (do not edit this line) */
