/* Generated By:JJTree: Do not edit this line. ASTAdditiveExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTAdditiveExpression extends SimpleNode {
  public ASTAdditiveExpression(int id) {
    super(id);
  }

  public ASTAdditiveExpression(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=30731376e30aef50a29c07417a08db7d (do not edit this line) */
