/* Generated By:JJTree: Do not edit this line. ASTAssertStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTAssertStatement extends SimpleNode {
  public ASTAssertStatement(int id) {
    super(id);
  }

  public ASTAssertStatement(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cef563710a35f023a51c19c2205ddf47 (do not edit this line) */
