/* Generated By:JJTree: Do not edit this line. ASTBitOrToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTBitOrToken extends SimpleNode {
  public ASTBitOrToken(int id) {
    super(id);
  }

  public ASTBitOrToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2f5c5c130e201f1833d1f4bb83970536 (do not edit this line) */
