/* Generated By:JJTree: Do not edit this line. ASTBitAndToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTBitAndToken extends SimpleNode {
  public ASTBitAndToken(int id) {
    super(id);
  }

  public ASTBitAndToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b88ce91709a963ab764a201c20b425bc (do not edit this line) */
