/* Generated By:JJTree: Do not edit this line. ASTBlockConstructor.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTBlockConstructor extends SimpleNode {
  public ASTBlockConstructor(int id) {
    super(id);
  }

  public ASTBlockConstructor(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2a20903bdafba9fe673da0b0a7aaa619 (do not edit this line) */
