/* Generated By:JJTree: Do not edit this line. ASTBreakToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTBreakToken extends SimpleNode {
  public ASTBreakToken(int id) {
    super(id);
  }

  public ASTBreakToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=475bff093350748da477fad9f2def5d9 (do not edit this line) */
