/* Generated By:JJTree: Do not edit this line. ASTBracket.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTBracket extends SimpleNode {
  public ASTBracket(int id) {
    super(id);
  }

  public ASTBracket(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0005c17e1f39baaf7888c351380b82bc (do not edit this line) */
