/* Generated By:JJTree: Do not edit this line. ASTBooleanLiteral.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTBooleanLiteral extends SimpleNode {
  public ASTBooleanLiteral(int id) {
    super(id);
  }

  public ASTBooleanLiteral(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2ecc9e6cb55c014ac4e87557ff32e9e1 (do not edit this line) */
