/* Generated By:JJTree: Do not edit this line. ASTClassToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTClassToken extends SimpleNode {
  public ASTClassToken(int id) {
    super(id);
  }

  public ASTClassToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=585d9f433de849261f513f6d5e6d2619 (do not edit this line) */
