/* Generated By:JJTree: Do not edit this line. ASTClassOrInterfaceBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTClassOrInterfaceBody extends SimpleNode {
  public ASTClassOrInterfaceBody(int id) {
    super(id);
  }

  public ASTClassOrInterfaceBody(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=af4e445e400a1d16db7535bdf8a996c1 (do not edit this line) */
