/* Generated By:JJTree: Do not edit this line. ASTCommaToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTCommaToken extends SimpleNode {
  public ASTCommaToken(int id) {
    super(id);
  }

  public ASTCommaToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9163733051768c6b2ae7924615282293 (do not edit this line) */
