/* Generated By:JJTree: Do not edit this line. ASTContinueToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTContinueToken extends SimpleNode {
  public ASTContinueToken(int id) {
    super(id);
  }

  public ASTContinueToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=14b743cb5837ce2ec0df344d2302414a (do not edit this line) */
