/* Generated By:JJTree: Do not edit this line. ASTClassOrInterfaceDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTClassOrInterfaceDeclaration extends SimpleNode {
  public ASTClassOrInterfaceDeclaration(int id) {
    super(id);
  }

  public ASTClassOrInterfaceDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1dd7bc459851c056936e15ee8883b797 (do not edit this line) */
