/* Generated By:JJTree: Do not edit this line. ASTClassOrInterfaceType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTClassOrInterfaceType extends SimpleNode {
  public ASTClassOrInterfaceType(int id) {
    super(id);
  }

  public ASTClassOrInterfaceType(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2ba2fbecc53615cb9feb8b35814bf20d (do not edit this line) */
