/* Generated By:JJTree: Do not edit this line. ASTCaseToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTCaseToken extends SimpleNode {
  public ASTCaseToken(int id) {
    super(id);
  }

  public ASTCaseToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7d8821a151bd54aed2ce6dd55d16f430 (do not edit this line) */
