/* Generated By:JJTree: Do not edit this line. ASTDoToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTDoToken extends SimpleNode {
  public ASTDoToken(int id) {
    super(id);
  }

  public ASTDoToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1d39bad074342aae984d0638110c5a7d (do not edit this line) */
