/* Generated By:JJTree: Do not edit this line. ASTDotToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTDotToken extends SimpleNode {
  public ASTDotToken(int id) {
    super(id);
  }

  public ASTDotToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=aef782d93b605f60cb7cfb2fcf3a62eb (do not edit this line) */
