/* Generated By:JJTree: Do not edit this line. ASTDecrToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTDecrToken extends SimpleNode {
  public ASTDecrToken(int id) {
    super(id);
  }

  public ASTDecrToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7ffaddcb151acf1482b4d34fc308d103 (do not edit this line) */
