/* Generated By:JJTree: Do not edit this line. ASTDefaultValue.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTDefaultValue extends SimpleNode {
  public ASTDefaultValue(int id) {
    super(id);
  }

  public ASTDefaultValue(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ea1757b0b6867b310ebe0d28152a3680 (do not edit this line) */
