/* Generated By:JJTree: Do not edit this line. ASTDefaultToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTDefaultToken extends SimpleNode {
  public ASTDefaultToken(int id) {
    super(id);
  }

  public ASTDefaultToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c2e1bcdee63b2fea9665831438cd4566 (do not edit this line) */
