/* Generated By:JJTree: Do not edit this line. ASTEnumDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTEnumDeclaration extends SimpleNode {
  public ASTEnumDeclaration(int id) {
    super(id);
  }

  public ASTEnumDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c091840506448593604b5e2e8d60caa3 (do not edit this line) */
