/* Generated By:JJTree: Do not edit this line. ASTElseToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTElseToken extends SimpleNode {
  public ASTElseToken(int id) {
    super(id);
  }

  public ASTElseToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=25a627dfa624f03b46c35f7ea029742e (do not edit this line) */
