/* Generated By:JJTree: Do not edit this line. ASTEqualityTokens.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTEqualityTokens extends SimpleNode {
  public ASTEqualityTokens(int id) {
    super(id);
  }

  public ASTEqualityTokens(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eee1baf60dd045efa42c6dd31c7557c8 (do not edit this line) */
