/* Generated By:JJTree: Do not edit this line. ASTExplicitConstructorInvocation.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTExplicitConstructorInvocation extends SimpleNode {
  public ASTExplicitConstructorInvocation(int id) {
    super(id);
  }

  public ASTExplicitConstructorInvocation(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=73879a39f2934eb60950d3112acf45a4 (do not edit this line) */
