/* Generated By:JJTree: Do not edit this line. ASTEqualityOperators.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTEqualityOperators extends SimpleNode {
  public ASTEqualityOperators(int id) {
    super(id);
  }

  public ASTEqualityOperators(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5029975688a2b3ddaa9f2bd5c6f2620e (do not edit this line) */
