/* Generated By:JJTree: Do not edit this line. ASTFormalParameterLookahead.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTFormalParameterLookahead extends SimpleNode {
  public ASTFormalParameterLookahead(int id) {
    super(id);
  }

  public ASTFormalParameterLookahead(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cebc3992ba3074c5f45f40de436d3c2e (do not edit this line) */
