/* Generated By:JJTree: Do not edit this line. ASTForInit.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTForInit extends SimpleNode {
  public ASTForInit(int id) {
    super(id);
  }

  public ASTForInit(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ec5fc108ca659c8976748503aa85c426 (do not edit this line) */
