/* Generated By:JJTree: Do not edit this line. ASTFinallyToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTFinallyToken extends SimpleNode {
  public ASTFinallyToken(int id) {
    super(id);
  }

  public ASTFinallyToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5dc8e0d5b8814414a13ab7759adccd60 (do not edit this line) */
