/* Generated By:JJTree: Do not edit this line. ASTForStatementRange.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTForStatementRange extends SimpleNode {
  public ASTForStatementRange(int id) {
    super(id);
  }

  public ASTForStatementRange(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9c5e08f2d2bb5328c1714a7fa2681294 (do not edit this line) */
