/* Generated By:JJTree: Do not edit this line. ASTFormalParameterLamda.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTFormalParameterLamda extends SimpleNode {
  public ASTFormalParameterLamda(int id) {
    super(id);
  }

  public ASTFormalParameterLamda(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8a5e0da769376d87ab993d60e5606540 (do not edit this line) */
