/* Generated By:JJTree: Do not edit this line. ASTFormalParametersLamda.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTFormalParametersLamda extends SimpleNode {
  public ASTFormalParametersLamda(int id) {
    super(id);
  }

  public ASTFormalParametersLamda(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ce856e7327f85aa810b2eceb6d5893ac (do not edit this line) */
