/* Generated By:JJTree: Do not edit this line. ASTInstanceOfToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTInstanceOfToken extends SimpleNode {
  public ASTInstanceOfToken(int id) {
    super(id);
  }

  public ASTInstanceOfToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a889b113f69e10e7ff0dfcb4755ea8f3 (do not edit this line) */
