/* Generated By:JJTree: Do not edit this line. ASTInitializer.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTInitializer extends SimpleNode {
  public ASTInitializer(int id) {
    super(id);
  }

  public ASTInitializer(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=709f46b820a58b41dc4d504f183bd8a8 (do not edit this line) */
