/* Generated By:JJTree: Do not edit this line. ASTInstanceOfExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTInstanceOfExpression extends SimpleNode {
  public ASTInstanceOfExpression(int id) {
    super(id);
  }

  public ASTInstanceOfExpression(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6e13c908190851c2eb1bbb07f8fba827 (do not edit this line) */
