/* Generated By:JJTree: Do not edit this line. ASTIncrToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTIncrToken extends SimpleNode {
  public ASTIncrToken(int id) {
    super(id);
  }

  public ASTIncrToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8d03bf76416207f389dee6d18b3323c8 (do not edit this line) */
