/* Generated By:JJTree: Do not edit this line. ASTLamdaBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTLamdaBody extends SimpleNode {
  public ASTLamdaBody(int id) {
    super(id);
  }

  public ASTLamdaBody(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=013e3fb99035a4f863e9885a3ae589d8 (do not edit this line) */
