/* Generated By:JJTree: Do not edit this line. ASTLamdaExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTLamdaExpression extends SimpleNode {
  public ASTLamdaExpression(int id) {
    super(id);
  }

  public ASTLamdaExpression(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9f9b75a92f37f6336936c1d3b4f7e3a9 (do not edit this line) */
