/* Generated By:JJTree: Do not edit this line. ASTLBracketToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTLBracketToken extends SimpleNode {
  public ASTLBracketToken(int id) {
    super(id);
  }

  public ASTLBracketToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0a0ffc034116235bccee2287bd51e034 (do not edit this line) */
