/* Generated By:JJTree: Do not edit this line. ASTLParenToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTLParenToken extends SimpleNode {
  public ASTLParenToken(int id) {
    super(id);
  }

  public ASTLParenToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=228e640edc5e912a394cee12d9d5e3e1 (do not edit this line) */
