/* Generated By:JJTree: Do not edit this line. ASTLShiftToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTLShiftToken extends SimpleNode {
  public ASTLShiftToken(int id) {
    super(id);
  }

  public ASTLShiftToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e62763042fa997bd1706e610cbd7c38a (do not edit this line) */
