/* Generated By:JJTree: Do not edit this line. ASTLamdaExpressionLookahead.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTLamdaExpressionLookahead extends SimpleNode {
  public ASTLamdaExpressionLookahead(int id) {
    super(id);
  }

  public ASTLamdaExpressionLookahead(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dac3c63536b61403eafcf7796d7e62bd (do not edit this line) */
