/* Generated By:JJTree: Do not edit this line. ASTLBraceToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTLBraceToken extends SimpleNode {
  public ASTLBraceToken(int id) {
    super(id);
  }

  public ASTLBraceToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2b736e22181252a688bd81b9996e33f1 (do not edit this line) */
