/* Generated By:JJTree: Do not edit this line. ASTLabeledStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTLabeledStatement extends SimpleNode {
  public ASTLabeledStatement(int id) {
    super(id);
  }

  public ASTLabeledStatement(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0a7d5a83ff97d7346da907a7dfaf0b94 (do not edit this line) */
