/* Generated By:JJTree: Do not edit this line. ASTMultiplicativeExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTMultiplicativeExpression extends SimpleNode {
  public ASTMultiplicativeExpression(int id) {
    super(id);
  }

  public ASTMultiplicativeExpression(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a7eeec9fda754af71ef6e3f57648a533 (do not edit this line) */
