/* Generated By:JJTree: Do not edit this line. ASTMemberValue.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTMemberValue extends SimpleNode {
  public ASTMemberValue(int id) {
    super(id);
  }

  public ASTMemberValue(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=57590e75cde6488395f5fa2c04e3e57d (do not edit this line) */
