/* Generated By:JJTree: Do not edit this line. ASTMemberValuePair.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTMemberValuePair extends SimpleNode {
  public ASTMemberValuePair(int id) {
    super(id);
  }

  public ASTMemberValuePair(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=12249936360a81906495e2add43e0637 (do not edit this line) */
