/* Generated By:JJTree: Do not edit this line. ASTMemberValueArrayInitializer.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTMemberValueArrayInitializer extends SimpleNode {
  public ASTMemberValueArrayInitializer(int id) {
    super(id);
  }

  public ASTMemberValueArrayInitializer(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=db03a12517985afe7d0a0bfe0231450a (do not edit this line) */
