/* Generated By:JJTree: Do not edit this line. ASTMethodDeclaratorResult.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTMethodDeclaratorResult extends SimpleNode {
  public ASTMethodDeclaratorResult(int id) {
    super(id);
  }

  public ASTMethodDeclaratorResult(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=154f68dba554641ad937368d9e1f8224 (do not edit this line) */
