/* Generated By:JJTree: Do not edit this line. ASTMultiplicativeTokens.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTMultiplicativeTokens extends SimpleNode {
  public ASTMultiplicativeTokens(int id) {
    super(id);
  }

  public ASTMultiplicativeTokens(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2ec3e81553baef8831a8b5ec5ee37f3e (do not edit this line) */
