/* Generated By:JJTree: Do not edit this line. ASTModifiers.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTModifiers extends SimpleNode {
  public ASTModifiers(int id) {
    super(id);
  }

  public ASTModifiers(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=89b3b0aeeec762858251c08cf4340020 (do not edit this line) */
