/* Generated By:JJTree: Do not edit this line. ASTMemberSelector.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTMemberSelector extends SimpleNode {
  public ASTMemberSelector(int id) {
    super(id);
  }

  public ASTMemberSelector(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=38684355e2d15ea45c9a597249744e87 (do not edit this line) */
