/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTMethodDeclarator extends SimpleNode {
  public ASTMethodDeclarator(int id) {
    super(id);
  }

  public ASTMethodDeclarator(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a9fd404ad15ec554a4a0b7fb376cc052 (do not edit this line) */
