/* Generated By:JJTree: Do not edit this line. ASTMultiplicativeOperation.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTMultiplicativeOperation extends SimpleNode {
  public ASTMultiplicativeOperation(int id) {
    super(id);
  }

  public ASTMultiplicativeOperation(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a1ec78e6ba05108f8540a4830477bdcb (do not edit this line) */
