/* Generated By:JJTree: Do not edit this line. ASTNormalAnnotation.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTNormalAnnotation extends SimpleNode {
  public ASTNormalAnnotation(int id) {
    super(id);
  }

  public ASTNormalAnnotation(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a25c96763802c29eca88c0b1db7f04ee (do not edit this line) */
