/* Generated By:JJTree: Do not edit this line. ASTNameEff.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTNameEff extends SimpleNode {
  public ASTNameEff(int id) {
    super(id);
  }

  public ASTNameEff(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=60a5a23d7428ceaebb455811c3a06d9d (do not edit this line) */
