/* Generated By:JJTree: Do not edit this line. ASTNewToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTNewToken extends SimpleNode {
  public ASTNewToken(int id) {
    super(id);
  }

  public ASTNewToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6f2657dee3892a97526141e9d3b82ab8 (do not edit this line) */
