/* Generated By:JJTree: Do not edit this line. ASTNotPlusMinusTokens.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTNotPlusMinusTokens extends SimpleNode {
  public ASTNotPlusMinusTokens(int id) {
    super(id);
  }

  public ASTNotPlusMinusTokens(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a6cfa3e23266c59a7ea6ccf034e3e8cc (do not edit this line) */
