/* Generated By:JJTree: Do not edit this line. ASTNameList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTNameList extends SimpleNode {
  public ASTNameList(int id) {
    super(id);
  }

  public ASTNameList(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4c1776f72e43cb6bdbf1d7c20e3e93c3 (do not edit this line) */
