/* Generated By:JJTree: Do not edit this line. ASTOrToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTOrToken extends SimpleNode {
  public ASTOrToken(int id) {
    super(id);
  }

  public ASTOrToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ed734aea533eba0ce67a67d8d216a593 (do not edit this line) */
