/* Generated By:JJTree: Do not edit this line. ASTPrimaryPrefix.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTPrimaryPrefix extends SimpleNode {
  public ASTPrimaryPrefix(int id) {
    super(id);
  }

  public ASTPrimaryPrefix(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bb580a2c3b351137e3d4c761f8d2024a (do not edit this line) */
