/* Generated By:JJTree: Do not edit this line. ASTPackageDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTPackageDeclaration extends SimpleNode {
  public ASTPackageDeclaration(int id) {
    super(id);
  }

  public ASTPackageDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0aa3813401a2d9f91d6f3e502738269b (do not edit this line) */
