/* Generated By:JJTree: Do not edit this line. ASTPrimitiveType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTPrimitiveType extends SimpleNode {
  public ASTPrimitiveType(int id) {
    super(id);
  }

  public ASTPrimitiveType(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=060d88bb0b3e2be4f3bcf04b37ad3ae9 (do not edit this line) */
