/* Generated By:JJTree: Do not edit this line. ASTRBraceToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTRBraceToken extends SimpleNode {
  public ASTRBraceToken(int id) {
    super(id);
  }

  public ASTRBraceToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=57a8eaa68c30eec8611ed04adbaef7fd (do not edit this line) */
