/* Generated By:JJTree: Do not edit this line. ASTRBracketToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTRBracketToken extends SimpleNode {
  public ASTRBracketToken(int id) {
    super(id);
  }

  public ASTRBracketToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3018389c7ed6fa4f501c26d5fa63ae95 (do not edit this line) */
