/* Generated By:JJTree: Do not edit this line. ASTReferenceType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTReferenceType extends SimpleNode {
  public ASTReferenceType(int id) {
    super(id);
  }

  public ASTReferenceType(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d90e1da9a3e691da366b51394167421b (do not edit this line) */
