/* Generated By:JJTree: Do not edit this line. ASTRUNSIGNEDSHIFT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTRUNSIGNEDSHIFT extends SimpleNode {
  public ASTRUNSIGNEDSHIFT(int id) {
    super(id);
  }

  public ASTRUNSIGNEDSHIFT(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6cda096411c7820f52ad7081970b6204 (do not edit this line) */
