/* Generated By:JJTree: Do not edit this line. ASTRSIGNEDSHIFT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTRSIGNEDSHIFT extends SimpleNode {
  public ASTRSIGNEDSHIFT(int id) {
    super(id);
  }

  public ASTRSIGNEDSHIFT(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9caf93dd37d450b0daad57afcf1f44e8 (do not edit this line) */
