/* Generated By:JJTree: Do not edit this line. ASTReturnToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTReturnToken extends SimpleNode {
  public ASTReturnToken(int id) {
    super(id);
  }

  public ASTReturnToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=01242280850c7c988f644982f45292cb (do not edit this line) */
