/* Generated By:JJTree: Do not edit this line. ASTRParenToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTRParenToken extends SimpleNode {
  public ASTRParenToken(int id) {
    super(id);
  }

  public ASTRParenToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4761b6419e5db6868809af8ff04cb9b4 (do not edit this line) */
