/* Generated By:JJTree: Do not edit this line. ASTResultType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTResultType extends SimpleNode {
  public ASTResultType(int id) {
    super(id);
  }

  public ASTResultType(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bacfd48a46a83fafd08b4909d180777d (do not edit this line) */
