/* Generated By:JJTree: Do not edit this line. ASTRelationTokens.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTRelationTokens extends SimpleNode {
  public ASTRelationTokens(int id) {
    super(id);
  }

  public ASTRelationTokens(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=20cf93072f1d25b678f17f9298a84791 (do not edit this line) */
