/* Generated By:JJTree: Do not edit this line. ASTRelationalExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTRelationalExpression extends SimpleNode {
  public ASTRelationalExpression(int id) {
    super(id);
  }

  public ASTRelationalExpression(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fbc5cd40757d10b4261c44cb28b04426 (do not edit this line) */
