/* Generated By:JJTree: Do not edit this line. ASTSingleMemberAnnotation.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTSingleMemberAnnotation extends SimpleNode {
  public ASTSingleMemberAnnotation(int id) {
    super(id);
  }

  public ASTSingleMemberAnnotation(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c12240c0258b85da446555cc98db461e (do not edit this line) */
