/* Generated By:JJTree: Do not edit this line. ASTStar.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTStar extends SimpleNode {
  public ASTStar(int id) {
    super(id);
  }

  public ASTStar(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=103ae87aa8f6b832ae41934a8ede4b43 (do not edit this line) */
