/* Generated By:JJTree: Do not edit this line. ASTSwitchToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTSwitchToken extends SimpleNode {
  public ASTSwitchToken(int id) {
    super(id);
  }

  public ASTSwitchToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8bd93c1e1ef1b98852eb94a9693f5241 (do not edit this line) */
