/* Generated By:JJTree: Do not edit this line. ASTSuperToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTSuperToken extends SimpleNode {
  public ASTSuperToken(int id) {
    super(id);
  }

  public ASTSuperToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ed219da9732fa4197c2526274a4f9f21 (do not edit this line) */
