/* Generated By:JJTree: Do not edit this line. ASTStatementExpressionList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTStatementExpressionList extends SimpleNode {
  public ASTStatementExpressionList(int id) {
    super(id);
  }

  public ASTStatementExpressionList(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ef741e7e15d8377d15c4bb6f7ebe4348 (do not edit this line) */
