/* Generated By:JJTree: Do not edit this line. ASTSemicolonToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTSemicolonToken extends SimpleNode {
  public ASTSemicolonToken(int id) {
    super(id);
  }

  public ASTSemicolonToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d807e84f59082a9cc183613efe728263 (do not edit this line) */
