/* Generated By:JJTree: Do not edit this line. ASTSwitchLabel.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTSwitchLabel extends SimpleNode {
  public ASTSwitchLabel(int id) {
    super(id);
  }

  public ASTSwitchLabel(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=787be04d151fbe9beb5a29c0f61014fd (do not edit this line) */
