/* Generated By:JJTree: Do not edit this line. ASTTryToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTTryToken extends SimpleNode {
  public ASTTryToken(int id) {
    super(id);
  }

  public ASTTryToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=df8e75c4134c3b790465067a1fc00894 (do not edit this line) */
