/* Generated By:JJTree: Do not edit this line. ASTTypeParameters.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTTypeParameters extends SimpleNode {
  public ASTTypeParameters(int id) {
    super(id);
  }

  public ASTTypeParameters(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8bdc11791cfdb2ae1f579248a4d65aaf (do not edit this line) */
