/* Generated By:JJTree: Do not edit this line. ASTTypeDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTTypeDeclaration extends SimpleNode {
  public ASTTypeDeclaration(int id) {
    super(id);
  }

  public ASTTypeDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=32758ef6ad0360b649ad8a65dbbb73fc (do not edit this line) */
