/* Generated By:JJTree: Do not edit this line. ASTTypeIdentifier.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTTypeIdentifier extends SimpleNode {
  public ASTTypeIdentifier(int id) {
    super(id);
  }

  public ASTTypeIdentifier(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a2c6b79326ff840f497aca9baa3bd839 (do not edit this line) */
