/* Generated By:JJTree: Do not edit this line. ASTTypeBound.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTTypeBound extends SimpleNode {
  public ASTTypeBound(int id) {
    super(id);
  }

  public ASTTypeBound(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d4cb07edaa104d1d90177bd4f339806c (do not edit this line) */
