/* Generated By:JJTree: Do not edit this line. ASTTypeParameter.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTTypeParameter extends SimpleNode {
  public ASTTypeParameter(int id) {
    super(id);
  }

  public ASTTypeParameter(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0875018f390465c2ce382502bd7fba8a (do not edit this line) */
