/* Generated By:JJTree: Do not edit this line. ASTThisToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTThisToken extends SimpleNode {
  public ASTThisToken(int id) {
    super(id);
  }

  public ASTThisToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2fd60b662000d770c52d4adbc4983703 (do not edit this line) */
