/* Generated By:JJTree: Do not edit this line. ASTTryStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTTryStatement extends SimpleNode {
  public ASTTryStatement(int id) {
    super(id);
  }

  public ASTTryStatement(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8e9e23f268a19d5d04f9abb8a6c2a654 (do not edit this line) */
