/* Generated By:JJTree: Do not edit this line. ASTThrowToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTThrowToken extends SimpleNode {
  public ASTThrowToken(int id) {
    super(id);
  }

  public ASTThrowToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=386f761a509b8b81e9f92c8739a294e5 (do not edit this line) */
