/* Generated By:JJTree: Do not edit this line. ASTUnaryTokens.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTUnaryTokens extends SimpleNode {
  public ASTUnaryTokens(int id) {
    super(id);
  }

  public ASTUnaryTokens(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7ead438352ed21dda967144cdc62beea (do not edit this line) */
