/* Generated By:JJTree: Do not edit this line. ASTVariableInitializer.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTVariableInitializer extends SimpleNode {
  public ASTVariableInitializer(int id) {
    super(id);
  }

  public ASTVariableInitializer(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e3ff25976bf742d89776dffe176afe14 (do not edit this line) */
