/* Generated By:JJTree: Do not edit this line. ASTVariableDeclaratorId.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTVariableDeclaratorId extends SimpleNode {
  public ASTVariableDeclaratorId(int id) {
    super(id);
  }

  public ASTVariableDeclaratorId(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2dcae9647bcbad6e08af876349ac4530 (do not edit this line) */
