/* Generated By:JJTree: Do not edit this line. ASTVarParameters.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTVarParameters extends SimpleNode {
  public ASTVarParameters(int id) {
    super(id);
  }

  public ASTVarParameters(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=649cefa563957127d5a936729fbeb3a4 (do not edit this line) */
