/* Generated By:JJTree: Do not edit this line. ASTWildcardBounds.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTWildcardBounds extends SimpleNode {
  public ASTWildcardBounds(int id) {
    super(id);
  }

  public ASTWildcardBounds(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0689fa4f77ef913fad97d3311e7dba6b (do not edit this line) */
