/* Generated By:JJTree: Do not edit this line. ASTXorToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.java;

public
class ASTXorToken extends SimpleNode {
  public ASTXorToken(int id) {
    super(id);
  }

  public ASTXorToken(JavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c9b19db8fb4b6a6fa3f9871e57e48546 (do not edit this line) */
