/* Generated By:JJTree: Do not edit this line. ASTArrayDimsAndInits.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTArrayDimsAndInits extends SimpleNode {
  public ASTArrayDimsAndInits(int id) {
    super(id);
  }

  public ASTArrayDimsAndInits(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9b0bf03d281d852148092e2a5e85c939 (do not edit this line) */
