/* Generated By:JJTree: Do not edit this line. ASTAndExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTAndExpression extends SimpleNode {
  public ASTAndExpression(int id) {
    super(id);
  }

  public ASTAndExpression(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8e28c81088055dddc476fcb28cc7be0a (do not edit this line) */
