/* Generated By:JJTree: Do not edit this line. ASTAssignToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTAssignToken extends SimpleNode {
  public ASTAssignToken(int id) {
    super(id);
  }

  public ASTAssignToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=02712cec7bfad51357a71d8bd9feb8d3 (do not edit this line) */
