/* Generated By:JJTree: Do not edit this line. ASTAdditiveTokens.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTAdditiveTokens extends SimpleNode {
  public ASTAdditiveTokens(int id) {
    super(id);
  }

  public ASTAdditiveTokens(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=76be1a77847d2fabf6e885f82143e5b2 (do not edit this line) */
