/* Generated By:JJTree: Do not edit this line. ASTArrowToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTArrowToken extends SimpleNode {
  public ASTArrowToken(int id) {
    super(id);
  }

  public ASTArrowToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ff17e220d41bebc2c984c157f457d63a (do not edit this line) */
