/* Generated By:JJTree: Do not edit this line. ASTBitOrToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTBitOrToken extends SimpleNode {
  public ASTBitOrToken(int id) {
    super(id);
  }

  public ASTBitOrToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=292a507a5ddbb57df4adabed40850596 (do not edit this line) */
