/* Generated By:JJTree: Do not edit this line. ASTBreakToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTBreakToken extends SimpleNode {
  public ASTBreakToken(int id) {
    super(id);
  }

  public ASTBreakToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0d71d74c40acdc5cb9f37a86231f1763 (do not edit this line) */
