/* Generated By:JJTree: Do not edit this line. ASTBlock.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTBlock extends SimpleNode {
  public ASTBlock(int id) {
    super(id);
  }

  public ASTBlock(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0acf89171661fb2352bf2313323a9fc7 (do not edit this line) */
