/* Generated By:JJTree: Do not edit this line. ASTBitAndToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTBitAndToken extends SimpleNode {
  public ASTBitAndToken(int id) {
    super(id);
  }

  public ASTBitAndToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=016a847fe828f03e2fd8c3e493d75580 (do not edit this line) */
