/* Generated By:JJTree: Do not edit this line. ASTCaseToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTCaseToken extends SimpleNode {
  public ASTCaseToken(int id) {
    super(id);
  }

  public ASTCaseToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0959ed09406bf00026e29fdb33f4aa84 (do not edit this line) */
