/* Generated By:JJTree: Do not edit this line. ASTCastLookahead.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTCastLookahead extends SimpleNode {
  public ASTCastLookahead(int id) {
    super(id);
  }

  public ASTCastLookahead(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f5e7f62781db2f27875a8fc1c31caa48 (do not edit this line) */
