/* Generated By:JJTree: Do not edit this line. ASTClassOrInterfaceBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTClassOrInterfaceBody extends SimpleNode {
  public ASTClassOrInterfaceBody(int id) {
    super(id);
  }

  public ASTClassOrInterfaceBody(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a3af5d303cf16609873efdbece6d8336 (do not edit this line) */
