/* Generated By:JJTree: Do not edit this line. ASTColonToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTColonToken extends SimpleNode {
  public ASTColonToken(int id) {
    super(id);
  }

  public ASTColonToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a44c8d871970cf2564175e040ed13a8f (do not edit this line) */
