/* Generated By:JJTree: Do not edit this line. ASTClassOrInterfaceType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTClassOrInterfaceType extends SimpleNode {
  public ASTClassOrInterfaceType(int id) {
    super(id);
  }

  public ASTClassOrInterfaceType(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=72fdc21741f40a11452e450704e6abfd (do not edit this line) */
