/* Generated By:JJTree: Do not edit this line. ASTDotToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTDotToken extends SimpleNode {
  public ASTDotToken(int id) {
    super(id);
  }

  public ASTDotToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c4dd487915955662cd77c8bab26216e8 (do not edit this line) */
