/* Generated By:JJTree: Do not edit this line. ASTDecrToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTDecrToken extends SimpleNode {
  public ASTDecrToken(int id) {
    super(id);
  }

  public ASTDecrToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d9c4e24c86697dcc99f0a99280c4b3c0 (do not edit this line) */
