/* Generated By:JJTree: Do not edit this line. ASTEqualityTokens.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTEqualityTokens extends SimpleNode {
  public ASTEqualityTokens(int id) {
    super(id);
  }

  public ASTEqualityTokens(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7f69be47a9ec8007b73a05d2d640a3fc (do not edit this line) */
