/* Generated By:JJTree: Do not edit this line. ASTExtendsList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTExtendsList extends SimpleNode {
  public ASTExtendsList(int id) {
    super(id);
  }

  public ASTExtendsList(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=55c9b3bf4e088a473e03a12bb463b5a9 (do not edit this line) */
