/* Generated By:JJTree: Do not edit this line. ASTElseToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTElseToken extends SimpleNode {
  public ASTElseToken(int id) {
    super(id);
  }

  public ASTElseToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c533adc2dc2a07b25c8c42e1307fdbf9 (do not edit this line) */
