/* Generated By:JJTree: Do not edit this line. ASTEqualityExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTEqualityExpression extends SimpleNode {
  public ASTEqualityExpression(int id) {
    super(id);
  }

  public ASTEqualityExpression(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=225f9ff1196205a0eb8fbd9256b36265 (do not edit this line) */
