/* Generated By:JJTree: Do not edit this line. ASTFormalParameters.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTFormalParameters extends SimpleNode {
  public ASTFormalParameters(int id) {
    super(id);
  }

  public ASTFormalParameters(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=95aed5eb244800e1cd28741b1ebb7521 (do not edit this line) */
