/* Generated By:JJTree: Do not edit this line. ASTFieldDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTFieldDeclaration extends SimpleNode {
  public ASTFieldDeclaration(int id) {
    super(id);
  }

  public ASTFieldDeclaration(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=11b2f5d0ce5f182a48f3ef5e10f23bc8 (do not edit this line) */
