/* Generated By:JJTree: Do not edit this line. ASTForInit.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTForInit extends SimpleNode {
  public ASTForInit(int id) {
    super(id);
  }

  public ASTForInit(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7dc9c35063f45753ad33be31246189e2 (do not edit this line) */
