/* Generated By:JJTree: Do not edit this line. ASTForStatementRange.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTForStatementRange extends SimpleNode {
  public ASTForStatementRange(int id) {
    super(id);
  }

  public ASTForStatementRange(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=31c5fd51f78123ef5c60e7a1f6e8735c (do not edit this line) */
