/* Generated By:JJTree: Do not edit this line. ASTHookToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTHookToken extends SimpleNode {
  public ASTHookToken(int id) {
    super(id);
  }

  public ASTHookToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=807b46b2ced961546d2682013d2cb3c4 (do not edit this line) */
