/* Generated By:JJTree: Do not edit this line. ASTImportDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTImportDeclaration extends SimpleNode {
  public ASTImportDeclaration(int id) {
    super(id);
  }

  public ASTImportDeclaration(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3bbc328096da2b3f6d54fc6ed5b16511 (do not edit this line) */
