/* Generated By:JJTree: Do not edit this line. ASTIfToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTIfToken extends SimpleNode {
  public ASTIfToken(int id) {
    super(id);
  }

  public ASTIfToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8fb959dda24ac4bfefa286c56cfd27be (do not edit this line) */
