/* Generated By:JJTree: Do not edit this line. ASTIfStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTIfStatement extends SimpleNode {
  public ASTIfStatement(int id) {
    super(id);
  }

  public ASTIfStatement(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b9e60740f2422e76475e38f3ddab6140 (do not edit this line) */
