/* Generated By:JJTree: Do not edit this line. ASTImportNamed.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTImportNamed extends SimpleNode {
  public ASTImportNamed(int id) {
    super(id);
  }

  public ASTImportNamed(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c7fe637c01d9e0046572422b92f5d7b9 (do not edit this line) */
