/* Generated By:JJTree: Do not edit this line. ASTLamdaExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTLamdaExpression extends SimpleNode {
  public ASTLamdaExpression(int id) {
    super(id);
  }

  public ASTLamdaExpression(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d3243b72ddbf561e5c974e5653d94a37 (do not edit this line) */
