/* Generated By:JJTree: Do not edit this line. ASTLBraceToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTLBraceToken extends SimpleNode {
  public ASTLBraceToken(int id) {
    super(id);
  }

  public ASTLBraceToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d7f6865ad6d5a6a72ba6ceed3d7b4e2f (do not edit this line) */
