/* Generated By:JJTree: Do not edit this line. ASTLiteralDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTLiteralDeclaration extends SimpleNode {
  public ASTLiteralDeclaration(int id) {
    super(id);
  }

  public ASTLiteralDeclaration(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=de0b878f2b3423f5b0af31120955f1cc (do not edit this line) */
