/* Generated By:JJTree: Do not edit this line. ASTLiteralField.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTLiteralField extends SimpleNode {
  public ASTLiteralField(int id) {
    super(id);
  }

  public ASTLiteralField(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=084b056d3caadf3ca9c3e39f9137b56c (do not edit this line) */
