/* Generated By:JJTree: Do not edit this line. ASTLParenToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTLParenToken extends SimpleNode {
  public ASTLParenToken(int id) {
    super(id);
  }

  public ASTLParenToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8eac865165e94fe7bbc671845f1337ea (do not edit this line) */
