/* Generated By:JJTree: Do not edit this line. ASTModifiers.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTModifiers extends SimpleNode {
  public ASTModifiers(int id) {
    super(id);
  }

  public ASTModifiers(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c4966dcbc8dc25701e114aa41a5ce328 (do not edit this line) */
