/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTMethodDeclarator extends SimpleNode {
  public ASTMethodDeclarator(int id) {
    super(id);
  }

  public ASTMethodDeclarator(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fd58bacfaab33f42f3ad71ab5bf8f07f (do not edit this line) */
