/* Generated By:JJTree: Do not edit this line. ASTMemberSelector.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTMemberSelector extends SimpleNode {
  public ASTMemberSelector(int id) {
    super(id);
  }

  public ASTMemberSelector(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b6957ddf6b10c4df42ba037fafb08e3b (do not edit this line) */
