/* Generated By:JJTree: Do not edit this line. ASTMethodReference.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTMethodReference extends SimpleNode {
  public ASTMethodReference(int id) {
    super(id);
  }

  public ASTMethodReference(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=103f905512e7fb7c257362e6c0f2849e (do not edit this line) */
