/* Generated By:JJTree: Do not edit this line. ASTMultiplicativeTokens.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTMultiplicativeTokens extends SimpleNode {
  public ASTMultiplicativeTokens(int id) {
    super(id);
  }

  public ASTMultiplicativeTokens(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=83835561e89b5cced625a6af77b46d15 (do not edit this line) */
