/* Generated By:JJTree: Do not edit this line. ASTNotPlusMinusTokens.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTNotPlusMinusTokens extends SimpleNode {
  public ASTNotPlusMinusTokens(int id) {
    super(id);
  }

  public ASTNotPlusMinusTokens(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=20eee28cf1cb1960f5774640df0e82b2 (do not edit this line) */
