/* Generated By:JJTree: Do not edit this line. ASTName.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTName extends SimpleNode {
  public ASTName(int id) {
    super(id);
  }

  public ASTName(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6a1df7bad3edf660cb3f598b75c70546 (do not edit this line) */
