/* Generated By:JJTree: Do not edit this line. ASTNewToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTNewToken extends SimpleNode {
  public ASTNewToken(int id) {
    super(id);
  }

  public ASTNewToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=77f2efd1186dc8bead855261195be227 (do not edit this line) */
