/* Generated By:JJTree: Do not edit this line. ASTOrToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTOrToken extends SimpleNode {
  public ASTOrToken(int id) {
    super(id);
  }

  public ASTOrToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=efcf90236d7bceb7e44d8e7ab059cda3 (do not edit this line) */
