/* Generated By:JJTree: Do not edit this line. ASTPrimarySuffix.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTPrimarySuffix extends SimpleNode {
  public ASTPrimarySuffix(int id) {
    super(id);
  }

  public ASTPrimarySuffix(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e85213c3c750479231d8a19c0dd90dd8 (do not edit this line) */
