/* Generated By:JJTree: Do not edit this line. ASTPrimitiveType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTPrimitiveType extends SimpleNode {
  public ASTPrimitiveType(int id) {
    super(id);
  }

  public ASTPrimitiveType(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6119c92e00ced0b08852c64a96370b07 (do not edit this line) */
