/* Generated By:JJTree: Do not edit this line. ASTReturnToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTReturnToken extends SimpleNode {
  public ASTReturnToken(int id) {
    super(id);
  }

  public ASTReturnToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b139b9eae0b0f0fc95e809a7989355d9 (do not edit this line) */
