/* Generated By:JJTree: Do not edit this line. ASTReferenceType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTReferenceType extends SimpleNode {
  public ASTReferenceType(int id) {
    super(id);
  }

  public ASTReferenceType(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9681b40a4c2a8e3cd26f54a49d5dabed (do not edit this line) */
