/* Generated By:JJTree: Do not edit this line. ASTRelationTokens.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTRelationTokens extends SimpleNode {
  public ASTRelationTokens(int id) {
    super(id);
  }

  public ASTRelationTokens(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=91bb02f4e5830b3d481f2f313aa557f5 (do not edit this line) */
