/* Generated By:JJTree: Do not edit this line. ASTRParenToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTRParenToken extends SimpleNode {
  public ASTRParenToken(int id) {
    super(id);
  }

  public ASTRParenToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=56a50094ed081c7dc6f34199f60bfae4 (do not edit this line) */
