/* Generated By:JJTree: Do not edit this line. ASTRBracketToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTRBracketToken extends SimpleNode {
  public ASTRBracketToken(int id) {
    super(id);
  }

  public ASTRBracketToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8bfc1ab18e0cc77990499eb093a24265 (do not edit this line) */
