/* Generated By:JJTree: Do not edit this line. ASTSwitchToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTSwitchToken extends SimpleNode {
  public ASTSwitchToken(int id) {
    super(id);
  }

  public ASTSwitchToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c8c5f1edc4fddf156e5e941b9e57af31 (do not edit this line) */
