/* Generated By:JJTree: Do not edit this line. ASTStatementExpressionList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTStatementExpressionList extends SimpleNode {
  public ASTStatementExpressionList(int id) {
    super(id);
  }

  public ASTStatementExpressionList(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fe3d266e4d9d76cd53d8ad3a9663914e (do not edit this line) */
