/* Generated By:JJTree: Do not edit this line. ASTStringLiteral.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTStringLiteral extends SimpleNode {
  public ASTStringLiteral(int id) {
    super(id);
  }

  public ASTStringLiteral(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8e62b432ffa310400e7c37d4fb09f4cb (do not edit this line) */
