/* Generated By:JJTree: Do not edit this line. ASTSemicolonToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTSemicolonToken extends SimpleNode {
  public ASTSemicolonToken(int id) {
    super(id);
  }

  public ASTSemicolonToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7bf799f3e723183647d041eefd2e257a (do not edit this line) */
