/* Generated By:JJTree: Do not edit this line. ASTStatementExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTStatementExpression extends SimpleNode {
  public ASTStatementExpression(int id) {
    super(id);
  }

  public ASTStatementExpression(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c3a979d229f7325b76f6b3dcfd7ad3b8 (do not edit this line) */
