/* Generated By:JJTree: Do not edit this line. ASTShiftExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTShiftExpression extends SimpleNode {
  public ASTShiftExpression(int id) {
    super(id);
  }

  public ASTShiftExpression(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cb3fb9f490716dedde4132cea17a43d0 (do not edit this line) */
