/* Generated By:JJTree: Do not edit this line. ASTSuperToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTSuperToken extends SimpleNode {
  public ASTSuperToken(int id) {
    super(id);
  }

  public ASTSuperToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5d9c38004d5f30c643a2ded076eada87 (do not edit this line) */
