/* Generated By:JJTree: Do not edit this line. ASTThrowStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTThrowStatement extends SimpleNode {
  public ASTThrowStatement(int id) {
    super(id);
  }

  public ASTThrowStatement(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7a5dccb65bb7b4d73547d57f9d2ccb73 (do not edit this line) */
