/* Generated By:JJTree: Do not edit this line. ASTTryToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTTryToken extends SimpleNode {
  public ASTTryToken(int id) {
    super(id);
  }

  public ASTTryToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=933fc2a1ec493292a73b98c28a2a0af0 (do not edit this line) */
