/* Generated By:JJTree: Do not edit this line. ASTThisToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTThisToken extends SimpleNode {
  public ASTThisToken(int id) {
    super(id);
  }

  public ASTThisToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d938eb8872bab379e6f531dbedd95e20 (do not edit this line) */
