/* Generated By:JJTree: Do not edit this line. ASTTypeIdentifier.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTTypeIdentifier extends SimpleNode {
  public ASTTypeIdentifier(int id) {
    super(id);
  }

  public ASTTypeIdentifier(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=57180ef32c219454c6d4144e2b97ffcf (do not edit this line) */
