/* Generated By:JJTree: Do not edit this line. ASTUnaryTokens.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTUnaryTokens extends SimpleNode {
  public ASTUnaryTokens(int id) {
    super(id);
  }

  public ASTUnaryTokens(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0ef11ddd16f2ee119e6220a2ebd0c197 (do not edit this line) */
