/* Generated By:JJTree: Do not edit this line. ASTUnaryExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTUnaryExpression extends SimpleNode {
  public ASTUnaryExpression(int id) {
    super(id);
  }

  public ASTUnaryExpression(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=55cbe16c77ba0de7bed4dd9de743b513 (do not edit this line) */
