/* Generated By:JJTree: Do not edit this line. ASTVoidType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTVoidType extends SimpleNode {
  public ASTVoidType(int id) {
    super(id);
  }

  public ASTVoidType(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c24ac70f6156f8026e3b28d304b4647d (do not edit this line) */
