/* Generated By:JJTree: Do not edit this line. ASTVariableDeclaratorId.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTVariableDeclaratorId extends SimpleNode {
  public ASTVariableDeclaratorId(int id) {
    super(id);
  }

  public ASTVariableDeclaratorId(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e44f0f79bdbfe8dcbd5d639c4966465d (do not edit this line) */
