/* Generated By:JJTree: Do not edit this line. ASTVarParameters.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTVarParameters extends SimpleNode {
  public ASTVarParameters(int id) {
    super(id);
  }

  public ASTVarParameters(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a9e0ddffdb471772c036e05c07009df9 (do not edit this line) */
