/* Generated By:JJTree: Do not edit this line. ASTWhileToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class ASTWhileToken extends SimpleNode {
  public ASTWhileToken(int id) {
    super(id);
  }

  public ASTWhileToken(EcmaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=302d9c9281ae8828c53fbd313feb0f01 (do not edit this line) */
