/* Generated By:JavaCC: Do not edit this line. EcmaParserTreeConstants.java Version 6.0_1 */
package ccbus.tool.parser.ecmascript;

public interface EcmaParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTIMPORTDECLARATION = 1;
  public int JJTIMPORTDEFAULT = 2;
  public int JJTIMPORTNAMED = 3;
  public int JJTMODIFIERS = 4;
  public int JJTMODIFIER = 5;
  public int JJTTYPEDECLARATION = 6;
  public int JJTCLASSORINTERFACEDECLARATION = 7;
  public int JJTTYPEIDENTIFIER = 8;
  public int JJTEXTENDSLIST = 9;
  public int JJTIMPLEMENTSLIST = 10;
  public int JJTTYPEPARAMETERS = 11;
  public int JJTTYPEPARAMETER = 12;
  public int JJTCLASSORINTERFACEBODY = 13;
  public int JJTCLASSORINTERFACEBODYDECLARATION = 14;
  public int JJTFIELDDECLARATION = 15;
  public int JJTLITERALDECLARATION = 16;
  public int JJTLITERALFIELD = 17;
  public int JJTLITERALMETHOD = 18;
  public int JJTVARIABLEDECLARATOR = 19;
  public int JJTASSIGNTOKEN = 20;
  public int JJTVARIABLEDECLARATORID = 21;
  public int JJTBRACKET = 22;
  public int JJTVARIABLEINITIALIZER = 23;
  public int JJTARRAYINITIALIZER = 24;
  public int JJTMETHODDECLARATION = 25;
  public int JJTSEMICOLONTOKEN = 26;
  public int JJTMETHODDECLARATOR = 27;
  public int JJTFORMALPARAMETERS = 28;
  public int JJTFORMALPARAMETER = 29;
  public int JJTVARPARAMETERS = 30;
  public int JJTIDENTIFIER = 31;
  public int JJTNAME = 32;
  public int JJTTYPE = 33;
  public int JJTREFERENCETYPE = 34;
  public int JJTCLASSORINTERFACETYPE = 35;
  public int JJTTYPEARGUMENTS = 36;
  public int JJTTYPEARGUMENT = 37;
  public int JJTPRIMITIVETYPE = 38;
  public int JJTRESULTTYPE = 39;
  public int JJTVOIDTYPE = 40;
  public int JJTEXPRESSION = 41;
  public int JJTLAMDAEXPRESSION = 42;
  public int JJTLAMDABODY = 43;
  public int JJTARROWTOKEN = 44;
  public int JJTASSIGNMENTOPERATOR = 45;
  public int JJTCONDITIONALEXPRESSION = 46;
  public int JJTHOOKTOKEN = 47;
  public int JJTCONDITIONALOREXPRESSION = 48;
  public int JJTORTOKEN = 49;
  public int JJTCONDITIONALANDEXPRESSION = 50;
  public int JJTANDTOKEN = 51;
  public int JJTINCLUSIVEOREXPRESSION = 52;
  public int JJTBITORTOKEN = 53;
  public int JJTEXCLUSIVEOREXPRESSION = 54;
  public int JJTXORTOKEN = 55;
  public int JJTANDEXPRESSION = 56;
  public int JJTBITANDTOKEN = 57;
  public int JJTEQUALITYEXPRESSION = 58;
  public int JJTEQUALITYTOKENS = 59;
  public int JJTINSTANCEOFEXPRESSION = 60;
  public int JJTRELATIONALEXPRESSION = 61;
  public int JJTRELATIONTOKENS = 62;
  public int JJTSHIFTEXPRESSION = 63;
  public int JJTLSHIFTTOKEN = 64;
  public int JJTADDITIVEEXPRESSION = 65;
  public int JJTADDITIVETOKENS = 66;
  public int JJTMULTIPLICATIVEEXPRESSION = 67;
  public int JJTMULTIPLICATIVETOKENS = 68;
  public int JJTUNARYEXPRESSION = 69;
  public int JJTUNARYTOKENS = 70;
  public int JJTPREINCREMENTEXPRESSION = 71;
  public int JJTINCRTOKEN = 72;
  public int JJTPREDECREMENTEXPRESSION = 73;
  public int JJTDECRTOKEN = 74;
  public int JJTUNARYEXPRESSIONNOTPLUSMINUS = 75;
  public int JJTNOTPLUSMINUSTOKENS = 76;
  public int JJTCASTLOOKAHEAD = 77;
  public int JJTPOSTFIXEXPRESSION = 78;
  public int JJTCASTEXPRESSION = 79;
  public int JJTPRIMARYEXPRESSION = 80;
  public int JJTMEMBERSELECTOR = 81;
  public int JJTDOTTOKEN = 82;
  public int JJTPRIMARYPREFIX = 83;
  public int JJTLPARENTOKEN = 84;
  public int JJTRPARENTOKEN = 85;
  public int JJTTHISTOKEN = 86;
  public int JJTSUPERTOKEN = 87;
  public int JJTPRIMARYSUFFIX = 88;
  public int JJTLBRACKETTOKEN = 89;
  public int JJTRBRACKETTOKEN = 90;
  public int JJTLITERAL = 91;
  public int JJTBOOLEANLITERAL = 92;
  public int JJTSTRINGLITERAL = 93;
  public int JJTNULLLITERAL = 94;
  public int JJTARGUMENTS = 95;
  public int JJTARGUMENTLIST = 96;
  public int JJTALLOCATIONEXPRESSION = 97;
  public int JJTNEWTOKEN = 98;
  public int JJTARRAYDIMSANDINITS = 99;
  public int JJTSTATEMENT = 100;
  public int JJTBLOCK = 101;
  public int JJTBLOCKSTATEMENT = 102;
  public int JJTLOCALVARIABLEDECLARATION = 103;
  public int JJTEMPTYSTATEMENT = 104;
  public int JJTSTATEMENTEXPRESSION = 105;
  public int JJTSWITCHSTATEMENT = 106;
  public int JJTSWITCHTOKEN = 107;
  public int JJTLBRACETOKEN = 108;
  public int JJTRBRACETOKEN = 109;
  public int JJTCASETOKEN = 110;
  public int JJTDEFAULTTOKEN = 111;
  public int JJTSWITCHLABEL = 112;
  public int JJTCOLONTOKEN = 113;
  public int JJTIFSTATEMENT = 114;
  public int JJTIFTOKEN = 115;
  public int JJTELSETOKEN = 116;
  public int JJTWHILESTATEMENT = 117;
  public int JJTWHILETOKEN = 118;
  public int JJTDOSTATEMENT = 119;
  public int JJTDOTOKEN = 120;
  public int JJTFORSTATEMENT = 121;
  public int JJTFORSTATEMENTRANGE = 122;
  public int JJTFORSTATEMENTLOOP = 123;
  public int JJTFORINIT = 124;
  public int JJTSTATEMENTEXPRESSIONLIST = 125;
  public int JJTCOMMATOKEN = 126;
  public int JJTFORUPDATE = 127;
  public int JJTBREAKSTATEMENT = 128;
  public int JJTBREAKTOKEN = 129;
  public int JJTCONTINUESTATEMENT = 130;
  public int JJTCONTINUETOKEN = 131;
  public int JJTRETURNSTATEMENT = 132;
  public int JJTRETURNTOKEN = 133;
  public int JJTTHROWSTATEMENT = 134;
  public int JJTTHROWTOKEN = 135;
  public int JJTTRYSTATEMENT = 136;
  public int JJTTRYTOKEN = 137;
  public int JJTCATCHTOKEN = 138;
  public int JJTFINALLYTOKEN = 139;
  public int JJTRUNSIGNEDSHIFT = 140;
  public int JJTRSIGNEDSHIFT = 141;
  public int JJTANNOTATION = 142;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "ImportDeclaration",
    "ImportDefault",
    "ImportNamed",
    "Modifiers",
    "Modifier",
    "TypeDeclaration",
    "ClassOrInterfaceDeclaration",
    "TypeIdentifier",
    "ExtendsList",
    "ImplementsList",
    "TypeParameters",
    "TypeParameter",
    "ClassOrInterfaceBody",
    "ClassOrInterfaceBodyDeclaration",
    "FieldDeclaration",
    "LiteralDeclaration",
    "LiteralField",
    "LiteralMethod",
    "VariableDeclarator",
    "AssignToken",
    "VariableDeclaratorId",
    "Bracket",
    "VariableInitializer",
    "ArrayInitializer",
    "MethodDeclaration",
    "SemicolonToken",
    "MethodDeclarator",
    "FormalParameters",
    "FormalParameter",
    "VarParameters",
    "Identifier",
    "Name",
    "Type",
    "ReferenceType",
    "ClassOrInterfaceType",
    "TypeArguments",
    "TypeArgument",
    "PrimitiveType",
    "ResultType",
    "VoidType",
    "Expression",
    "LamdaExpression",
    "LamdaBody",
    "ArrowToken",
    "AssignmentOperator",
    "ConditionalExpression",
    "HookToken",
    "ConditionalOrExpression",
    "OrToken",
    "ConditionalAndExpression",
    "AndToken",
    "InclusiveOrExpression",
    "BitOrToken",
    "ExclusiveOrExpression",
    "XorToken",
    "AndExpression",
    "BitAndToken",
    "EqualityExpression",
    "EqualityTokens",
    "InstanceOfExpression",
    "RelationalExpression",
    "RelationTokens",
    "ShiftExpression",
    "LShiftToken",
    "AdditiveExpression",
    "AdditiveTokens",
    "MultiplicativeExpression",
    "MultiplicativeTokens",
    "UnaryExpression",
    "UnaryTokens",
    "PreIncrementExpression",
    "IncrToken",
    "PreDecrementExpression",
    "DecrToken",
    "UnaryExpressionNotPlusMinus",
    "NotPlusMinusTokens",
    "CastLookahead",
    "PostfixExpression",
    "CastExpression",
    "PrimaryExpression",
    "MemberSelector",
    "DotToken",
    "PrimaryPrefix",
    "LParenToken",
    "RParenToken",
    "ThisToken",
    "SuperToken",
    "PrimarySuffix",
    "LBracketToken",
    "RBracketToken",
    "Literal",
    "BooleanLiteral",
    "StringLiteral",
    "NullLiteral",
    "Arguments",
    "ArgumentList",
    "AllocationExpression",
    "NewToken",
    "ArrayDimsAndInits",
    "Statement",
    "Block",
    "BlockStatement",
    "LocalVariableDeclaration",
    "EmptyStatement",
    "StatementExpression",
    "SwitchStatement",
    "SwitchToken",
    "LBraceToken",
    "RBraceToken",
    "CaseToken",
    "DefaultToken",
    "SwitchLabel",
    "ColonToken",
    "IfStatement",
    "IfToken",
    "ElseToken",
    "WhileStatement",
    "WhileToken",
    "DoStatement",
    "DoToken",
    "ForStatement",
    "ForStatementRange",
    "ForStatementLoop",
    "ForInit",
    "StatementExpressionList",
    "CommaToken",
    "ForUpdate",
    "BreakStatement",
    "BreakToken",
    "ContinueStatement",
    "ContinueToken",
    "ReturnStatement",
    "ReturnToken",
    "ThrowStatement",
    "ThrowToken",
    "TryStatement",
    "TryToken",
    "CatchToken",
    "FinallyToken",
    "RUNSIGNEDSHIFT",
    "RSIGNEDSHIFT",
    "Annotation",
  };
}
/* JavaCC - OriginalChecksum=45ea61446816b25168b4fcbd1e851f65 (do not edit this line) */
