/* Generated By:JJTree&JavaCC: Do not edit this line. EcmaParserConstants.java */
package ccbus.tool.parser.ecmascript;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EcmaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 9;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 10;
  /** RegularExpression Id. */
  int ABSTRACT = 12;
  /** RegularExpression Id. */
  int ASSERT = 13;
  /** RegularExpression Id. */
  int ANY = 14;
  /** RegularExpression Id. */
  int BOOLEAN = 15;
  /** RegularExpression Id. */
  int BREAK = 16;
  /** RegularExpression Id. */
  int BYTE = 17;
  /** RegularExpression Id. */
  int CASE = 18;
  /** RegularExpression Id. */
  int CATCH = 19;
  /** RegularExpression Id. */
  int CHAR = 20;
  /** RegularExpression Id. */
  int EXPORT = 21;
  /** RegularExpression Id. */
  int CLASS = 22;
  /** RegularExpression Id. */
  int CONST = 23;
  /** RegularExpression Id. */
  int CONTINUE = 24;
  /** RegularExpression Id. */
  int _DEFAULT = 25;
  /** RegularExpression Id. */
  int DO = 26;
  /** RegularExpression Id. */
  int DOUBLE = 27;
  /** RegularExpression Id. */
  int ELSE = 28;
  /** RegularExpression Id. */
  int ENUM = 29;
  /** RegularExpression Id. */
  int EXTENDS = 30;
  /** RegularExpression Id. */
  int FALSE = 31;
  /** RegularExpression Id. */
  int FINAL = 32;
  /** RegularExpression Id. */
  int FINALLY = 33;
  /** RegularExpression Id. */
  int FLOAT = 34;
  /** RegularExpression Id. */
  int FOR = 35;
  /** RegularExpression Id. */
  int GOTO = 36;
  /** RegularExpression Id. */
  int IF = 37;
  /** RegularExpression Id. */
  int IMPLEMENTS = 38;
  /** RegularExpression Id. */
  int IMPORT = 39;
  /** RegularExpression Id. */
  int FROM = 40;
  /** RegularExpression Id. */
  int INSTANCEOF = 41;
  /** RegularExpression Id. */
  int INT = 42;
  /** RegularExpression Id. */
  int INTERFACE = 43;
  /** RegularExpression Id. */
  int LONG = 44;
  /** RegularExpression Id. */
  int NATIVE = 45;
  /** RegularExpression Id. */
  int NEW = 46;
  /** RegularExpression Id. */
  int NUMBER = 47;
  /** RegularExpression Id. */
  int NULL = 48;
  /** RegularExpression Id. */
  int PACKAGE = 49;
  /** RegularExpression Id. */
  int PRIVATE = 50;
  /** RegularExpression Id. */
  int PROTECTED = 51;
  /** RegularExpression Id. */
  int PUBLIC = 52;
  /** RegularExpression Id. */
  int RETURN = 53;
  /** RegularExpression Id. */
  int STRING = 54;
  /** RegularExpression Id. */
  int SYMBOL = 55;
  /** RegularExpression Id. */
  int SHORT = 56;
  /** RegularExpression Id. */
  int STATIC = 57;
  /** RegularExpression Id. */
  int STRICTFP = 58;
  /** RegularExpression Id. */
  int SUPER = 59;
  /** RegularExpression Id. */
  int SWITCH = 60;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 61;
  /** RegularExpression Id. */
  int THIS = 62;
  /** RegularExpression Id. */
  int THROW = 63;
  /** RegularExpression Id. */
  int THROWS = 64;
  /** RegularExpression Id. */
  int TRANSIENT = 65;
  /** RegularExpression Id. */
  int TRUE = 66;
  /** RegularExpression Id. */
  int TRY = 67;
  /** RegularExpression Id. */
  int VOID = 68;
  /** RegularExpression Id. */
  int VOLATILE = 69;
  /** RegularExpression Id. */
  int WHILE = 70;
  /** RegularExpression Id. */
  int LET = 71;
  /** RegularExpression Id. */
  int OF = 72;
  /** RegularExpression Id. */
  int FUNCTION = 73;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 74;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 75;
  /** RegularExpression Id. */
  int HEX_LITERAL = 76;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 77;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 78;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 79;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 80;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 81;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 82;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 83;
  /** RegularExpression Id. */
  int STRING_LITERAL = 84;
  /** RegularExpression Id. */
  int IDENTIFIER = 85;
  /** RegularExpression Id. */
  int LETTER = 86;
  /** RegularExpression Id. */
  int PART_LETTER = 87;
  /** RegularExpression Id. */
  int LPAREN = 88;
  /** RegularExpression Id. */
  int RPAREN = 89;
  /** RegularExpression Id. */
  int LBRACE = 90;
  /** RegularExpression Id. */
  int RBRACE = 91;
  /** RegularExpression Id. */
  int LBRACKET = 92;
  /** RegularExpression Id. */
  int RBRACKET = 93;
  /** RegularExpression Id. */
  int SEMICOLON = 94;
  /** RegularExpression Id. */
  int COMMA = 95;
  /** RegularExpression Id. */
  int DOT = 96;
  /** RegularExpression Id. */
  int AT = 97;
  /** RegularExpression Id. */
  int ASSIGN = 98;
  /** RegularExpression Id. */
  int LT = 99;
  /** RegularExpression Id. */
  int BANG = 100;
  /** RegularExpression Id. */
  int TILDE = 101;
  /** RegularExpression Id. */
  int HOOK = 102;
  /** RegularExpression Id. */
  int COLON = 103;
  /** RegularExpression Id. */
  int EQ = 104;
  /** RegularExpression Id. */
  int LE = 105;
  /** RegularExpression Id. */
  int GE = 106;
  /** RegularExpression Id. */
  int NE = 107;
  /** RegularExpression Id. */
  int SC_OR = 108;
  /** RegularExpression Id. */
  int SC_AND = 109;
  /** RegularExpression Id. */
  int INCR = 110;
  /** RegularExpression Id. */
  int DECR = 111;
  /** RegularExpression Id. */
  int PLUS = 112;
  /** RegularExpression Id. */
  int MINUS = 113;
  /** RegularExpression Id. */
  int STAR = 114;
  /** RegularExpression Id. */
  int SLASH = 115;
  /** RegularExpression Id. */
  int BIT_AND = 116;
  /** RegularExpression Id. */
  int BIT_OR = 117;
  /** RegularExpression Id. */
  int XOR = 118;
  /** RegularExpression Id. */
  int REM = 119;
  /** RegularExpression Id. */
  int LSHIFT = 120;
  /** RegularExpression Id. */
  int PLUSASSIGN = 121;
  /** RegularExpression Id. */
  int MINUSASSIGN = 122;
  /** RegularExpression Id. */
  int STARASSIGN = 123;
  /** RegularExpression Id. */
  int SLASHASSIGN = 124;
  /** RegularExpression Id. */
  int ANDASSIGN = 125;
  /** RegularExpression Id. */
  int ORASSIGN = 126;
  /** RegularExpression Id. */
  int XORASSIGN = 127;
  /** RegularExpression Id. */
  int REMASSIGN = 128;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 129;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 130;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 131;
  /** RegularExpression Id. */
  int ELLIPSIS = 132;
  /** RegularExpression Id. */
  int PARENTDIR = 133;
  /** RegularExpression Id. */
  int ARROW = 134;
  /** RegularExpression Id. */
  int SINGLE_QUOTE = 135;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 136;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 137;
  /** RegularExpression Id. */
  int GT = 138;
  /** RegularExpression Id. */
  int STUFF_TO_IGNORE = 140;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 11>",
    "\"abstract\"",
    "\"assert\"",
    "\"any\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"export\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"from\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"number\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"string\"",
    "\"symbol\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"let\"",
    "\"of\"",
    "\"function\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\"..\"",
    "\"=>\"",
    "\"\\\'\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
    "\"\\u001a\"",
    "<STUFF_TO_IGNORE>",
  };

}
