/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.ecmascript;

public
class SimpleNode extends ccbus.tool.intermediate.SimpleNode  implements Node {

  protected EcmaParser parser;

  public SimpleNode(int i) {
    super(i);
  }

  public SimpleNode(EcmaParser p, int i) {
    super(i);
    parser = p;
  }
}

/* JavaCC - OriginalChecksum=6c90c52d1e8c9a330cf5a1cf882075b6 (do not edit this line) */
