/* Generated By:JJTree: Do not edit this line. ASTCompilationUnit.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.react;

public
class ASTCompilationUnit extends SimpleNode {
  public ASTCompilationUnit(int id) {
    super(id);
  }

  public ASTCompilationUnit(ReactParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=da46b5c04c87bee2ea26b5c949f3fe9f (do not edit this line) */
