/* Generated By:JJTree: Do not edit this line. ASTImportName.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.react;

public
class ASTImportName extends SimpleNode {
  public ASTImportName(int id) {
    super(id);
  }

  public ASTImportName(ReactParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=35b4b20b4f0933a50fcc5213c97d688d (do not edit this line) */
