/* Generated By:JJTree: Do not edit this line. ASTRenderDeclarations.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.react;

public
class ASTRenderDeclarations extends SimpleNode {
  public ASTRenderDeclarations(int id) {
    super(id);
  }

  public ASTRenderDeclarations(ReactParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f184191c4ad2e2ba62fcd171e30149d4 (do not edit this line) */
