/* Generated By:JJTree: Do not edit this line. ASTRenderDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.react;

public
class ASTRenderDeclaration extends SimpleNode {
  public ASTRenderDeclaration(int id) {
    super(id);
  }

  public ASTRenderDeclaration(ReactParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0297b6bc84b803172d9b2e1eb291dd2a (do not edit this line) */
