/* Generated By:JJTree: Do not edit this line. ASTArgumentExpressionList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTArgumentExpressionList extends SimpleNode {
  public ASTArgumentExpressionList(int id) {
    super(id);
  }

  public ASTArgumentExpressionList(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=04e201d9576e7b01ed56828d51b98b74 (do not edit this line) */
