/* Generated By:JJTree: Do not edit this line. ASTAssignmentExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTAssignmentExpression extends SimpleNode {
  public ASTAssignmentExpression(int id) {
    super(id);
  }

  public ASTAssignmentExpression(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8c954d32b96f9445a9938d556b746e33 (do not edit this line) */
