/* Generated By:JJTree: Do not edit this line. ASTBitwiseAndExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTBitwiseAndExpression extends SimpleNode {
  public ASTBitwiseAndExpression(int id) {
    super(id);
  }

  public ASTBitwiseAndExpression(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b2efc17cad08ee31dfbb9db19c2476bd (do not edit this line) */
