/* Generated By:JJTree: Do not edit this line. ASTBitwiseXorExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTBitwiseXorExpression extends SimpleNode {
  public ASTBitwiseXorExpression(int id) {
    super(id);
  }

  public ASTBitwiseXorExpression(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=40242844620bccd8a025e4b3a7e1959a (do not edit this line) */
