/* Generated By:JJTree: Do not edit this line. ASTCompoundStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTCompoundStatement extends SimpleNode {
  public ASTCompoundStatement(int id) {
    super(id);
  }

  public ASTCompoundStatement(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f32fe610e79919a208b5e562fbc1ece3 (do not edit this line) */
