/* Generated By:JJTree: Do not edit this line. ASTClassMembers.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTClassMembers extends SimpleNode {
  public ASTClassMembers(int id) {
    super(id);
  }

  public ASTClassMembers(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f116e5fc7764ce71e916cee89cf82d4c (do not edit this line) */
