/* Generated By:JJTree: Do not edit this line. ASTDoubleStringLiteral.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTDoubleStringLiteral extends SimpleNode {
  public ASTDoubleStringLiteral(int id) {
    super(id);
  }

  public ASTDoubleStringLiteral(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dd60e5d0156747071e46114e8e56018c (do not edit this line) */
