/* Generated By:JJTree: Do not edit this line. ASTDefineStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTDefineStatement extends SimpleNode {
  public ASTDefineStatement(int id) {
    super(id);
  }

  public ASTDefineStatement(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6bda0b341257294f3420f7f37f93ddd0 (do not edit this line) */
