/* Generated By:JJTree: Do not edit this line. ASTEmbeddedHtml.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTEmbeddedHtml extends SimpleNode {
  public ASTEmbeddedHtml(int id) {
    super(id);
  }

  public ASTEmbeddedHtml(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fbc976d336639c20d1594452dee96155 (do not edit this line) */
