/* Generated By:JJTree: Do not edit this line. ASTExpressionStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTExpressionStatement extends SimpleNode {
  public ASTExpressionStatement(int id) {
    super(id);
  }

  public ASTExpressionStatement(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e300ef03614567414ed91626429ccc5a (do not edit this line) */
