/* Generated By:JJTree: Do not edit this line. ASTEndOfStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTEndOfStatement extends SimpleNode {
  public ASTEndOfStatement(int id) {
    super(id);
  }

  public ASTEndOfStatement(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f3cec82639899cbbc7a3202b3706e08a (do not edit this line) */
