/* Generated By:JJTree: Do not edit this line. ASTHtmlBlock.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTHtmlBlock extends SimpleNode {
  public ASTHtmlBlock(int id) {
    super(id);
  }

  public ASTHtmlBlock(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2c8a3da125987beea1805268850a9db1 (do not edit this line) */
