/* Generated By:JJTree: Do not edit this line. ASTInterfaceMembers.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTInterfaceMembers extends SimpleNode {
  public ASTInterfaceMembers(int id) {
    super(id);
  }

  public ASTInterfaceMembers(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=26f8afcc48c9a69b31e970cf78054e5a (do not edit this line) */
