/* Generated By:JJTree: Do not edit this line. ASTInterfaceMember.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTInterfaceMember extends SimpleNode {
  public ASTInterfaceMember(int id) {
    super(id);
  }

  public ASTInterfaceMember(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=109bfb04734da198fc6c5098583bcf77 (do not edit this line) */
