/* Generated By:JJTree: Do not edit this line. ASTInterfaceDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTInterfaceDeclaration extends SimpleNode {
  public ASTInterfaceDeclaration(int id) {
    super(id);
  }

  public ASTInterfaceDeclaration(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d591a6be1e337b9a7d9c83f09d39f731 (do not edit this line) */
