/* Generated By:JJTree: Do not edit this line. ASTIncludeStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTIncludeStatement extends SimpleNode {
  public ASTIncludeStatement(int id) {
    super(id);
  }

  public ASTIncludeStatement(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=993efe84e7d415dc5afa3b5877cf6c01 (do not edit this line) */
