/* Generated By:JJTree: Do not edit this line. ASTLogical_Or_Expression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTLogical_Or_Expression extends SimpleNode {
  public ASTLogical_Or_Expression(int id) {
    super(id);
  }

  public ASTLogical_Or_Expression(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=38ce92379245fc99aab675bc1aa031cf (do not edit this line) */
