/* Generated By:JJTree: Do not edit this line. ASTLogicalTextAndExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTLogicalTextAndExpression extends SimpleNode {
  public ASTLogicalTextAndExpression(int id) {
    super(id);
  }

  public ASTLogicalTextAndExpression(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=82d1845293a08f16dc8b252654b1fc7e (do not edit this line) */
