/* Generated By:JJTree: Do not edit this line. ASTLogicalTextXorExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTLogicalTextXorExpression extends SimpleNode {
  public ASTLogicalTextXorExpression(int id) {
    super(id);
  }

  public ASTLogicalTextXorExpression(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4ccf62ef1e3bc495becf169f5bcea3b7 (do not edit this line) */
