/* Generated By:JJTree: Do not edit this line. ASTLogical_And_Expression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTLogical_And_Expression extends SimpleNode {
  public ASTLogical_And_Expression(int id) {
    super(id);
  }

  public ASTLogical_And_Expression(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c486bdad78277fa0345ed5040d7e0eb (do not edit this line) */
