/* Generated By:JJTree: Do not edit this line. ASTLogicalTextOrExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTLogicalTextOrExpression extends SimpleNode {
  public ASTLogicalTextOrExpression(int id) {
    super(id);
  }

  public ASTLogicalTextOrExpression(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7e8c18ec571f63cbc2ffaf15ee5d1206 (do not edit this line) */
