/* Generated By:JJTree: Do not edit this line. ASTMemberDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTMemberDeclaration extends SimpleNode {
  public ASTMemberDeclaration(int id) {
    super(id);
  }

  public ASTMemberDeclaration(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cfbae02bd1f2ddd7355f4b48acd29a32 (do not edit this line) */
