/* Generated By:JJTree: Do not edit this line. ASTPostfixExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTPostfixExpression extends SimpleNode {
  public ASTPostfixExpression(int id) {
    super(id);
  }

  public ASTPostfixExpression(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7e6ae126ee2488f3124c745dace0b9db (do not edit this line) */
