/* Generated By:JJTree: Do not edit this line. ASTParameter.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTParameter extends SimpleNode {
  public ASTParameter(int id) {
    super(id);
  }

  public ASTParameter(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=66dafffd17dec48acb889670d7502321 (do not edit this line) */
