/* Generated By:JJTree: Do not edit this line. ASTPrefixIncDecExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTPrefixIncDecExpression extends SimpleNode {
  public ASTPrefixIncDecExpression(int id) {
    super(id);
  }

  public ASTPrefixIncDecExpression(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=714237352223f0227cafd29945bf346e (do not edit this line) */
