/* Generated By:JJTree: Do not edit this line. ASTParameterList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTParameterList extends SimpleNode {
  public ASTParameterList(int id) {
    super(id);
  }

  public ASTParameterList(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1c337f6364ca6b7e43dce8437d238519 (do not edit this line) */
