/* Generated By:JJTree: Do not edit this line. ASTString.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTString extends SimpleNode {
  public ASTString(int id) {
    super(id);
  }

  public ASTString(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f92d98d24318bf971285efc2d60f2178 (do not edit this line) */
