/* Generated By:JJTree: Do not edit this line. ASTUnaryExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTUnaryExpression extends SimpleNode {
  public ASTUnaryExpression(int id) {
    super(id);
  }

  public ASTUnaryExpression(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=848de3c7601e8f1ca46b8141935886a1 (do not edit this line) */
