/* Generated By:JJTree: Do not edit this line. ASTVariableDeclarator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTVariableDeclarator extends SimpleNode {
  public ASTVariableDeclarator(int id) {
    super(id);
  }

  public ASTVariableDeclarator(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e6f3ed593bcd5135a84c634b7adfc501 (do not edit this line) */
