/* Generated By:JJTree: Do not edit this line. ASTVariable.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTVariable extends SimpleNode {
  public ASTVariable(int id) {
    super(id);
  }

  public ASTVariable(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=da25ab0db3a86ba91f6bb0d1da71e736 (do not edit this line) */
