/* Generated By:JJTree: Do not edit this line. ASTVisibility.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.php;

public
class ASTVisibility extends SimpleNode {
  public ASTVisibility(int id) {
    super(id);
  }

  public ASTVisibility(PhpParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b09b705f9166dbb5e587b12625466717 (do not edit this line) */
