/* Generated By:JJTree: Do not edit this line. ASTAdditiveExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.egaa;

public
class ASTAdditiveExpression extends SimpleNode {
  public ASTAdditiveExpression(int id) {
    super(id);
  }

  public ASTAdditiveExpression(Eg1 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4ccef3aa8daf970498cd3e664642d350 (do not edit this line) */
