/* Generated By:JJTree: Do not edit this line. ASTMultiplicativeExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.egaa;

public
class ASTMultiplicativeExpression extends SimpleNode {
  public ASTMultiplicativeExpression(int id) {
    super(id);
  }

  public ASTMultiplicativeExpression(Eg1 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0c538f3993fd477b44d74b55b48b3bc5 (do not edit this line) */
