/* Generated By:JJTree: Do not edit this line. ASTSumOp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ccbus.tool.parser.egaa;

public
class ASTSumOp extends SimpleNode {
  public ASTSumOp(int id) {
    super(id);
  }

  public ASTSumOp(Eg1 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ca87e7e1b93f13fe32482e0f45fac2c7 (do not edit this line) */
