/* Generated By:JavaCC: Do not edit this line. QueryConstants.java */
package ccbus.dbtool.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QueryConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SELECT = 5;
  /** RegularExpression Id. */
  int FROM = 6;
  /** RegularExpression Id. */
  int JOIN = 7;
  /** RegularExpression Id. */
  int SEMICOLON = 8;
  /** RegularExpression Id. */
  int DOT = 9;
  /** RegularExpression Id. */
  int COMMA = 10;
  /** RegularExpression Id. */
  int AS = 11;
  /** RegularExpression Id. */
  int IDENTIFIER = 12;
  /** RegularExpression Id. */
  int UNEXPECTED = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"select\"",
    "\"from\"",
    "\"join\"",
    "\";\"",
    "\".\"",
    "\",\"",
    "\"as\"",
    "<IDENTIFIER>",
    "<UNEXPECTED>",
  };

}
